// Generated by gencpp from file uuv_control_msgs/BottomSearchRequest.msg
// DO NOT EDIT!


#ifndef UUV_CONTROL_MSGS_MESSAGE_BOTTOMSEARCHREQUEST_H
#define UUV_CONTROL_MSGS_MESSAGE_BOTTOMSEARCHREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace uuv_control_msgs
{
template <class ContainerAllocator>
struct BottomSearchRequest_
{
  typedef BottomSearchRequest_<ContainerAllocator> Type;

  BottomSearchRequest_()
    {
    }
  BottomSearchRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::uuv_control_msgs::BottomSearchRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uuv_control_msgs::BottomSearchRequest_<ContainerAllocator> const> ConstPtr;

}; // struct BottomSearchRequest_

typedef ::uuv_control_msgs::BottomSearchRequest_<std::allocator<void> > BottomSearchRequest;

typedef boost::shared_ptr< ::uuv_control_msgs::BottomSearchRequest > BottomSearchRequestPtr;
typedef boost::shared_ptr< ::uuv_control_msgs::BottomSearchRequest const> BottomSearchRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uuv_control_msgs::BottomSearchRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uuv_control_msgs::BottomSearchRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace uuv_control_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::uuv_control_msgs::BottomSearchRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uuv_control_msgs::BottomSearchRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uuv_control_msgs::BottomSearchRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uuv_control_msgs::BottomSearchRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uuv_control_msgs::BottomSearchRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uuv_control_msgs::BottomSearchRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uuv_control_msgs::BottomSearchRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::uuv_control_msgs::BottomSearchRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::uuv_control_msgs::BottomSearchRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uuv_control_msgs/BottomSearchRequest";
  }

  static const char* value(const ::uuv_control_msgs::BottomSearchRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uuv_control_msgs::BottomSearchRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::uuv_control_msgs::BottomSearchRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uuv_control_msgs::BottomSearchRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BottomSearchRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uuv_control_msgs::BottomSearchRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::uuv_control_msgs::BottomSearchRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // UUV_CONTROL_MSGS_MESSAGE_BOTTOMSEARCHREQUEST_H
