// Generated by gencpp from file uuv_control_msgs/BottomSearch.msg
// DO NOT EDIT!


#ifndef UUV_CONTROL_MSGS_MESSAGE_BOTTOMSEARCH_H
#define UUV_CONTROL_MSGS_MESSAGE_BOTTOMSEARCH_H

#include <ros/service_traits.h>


#include <uuv_control_msgs/BottomSearchRequest.h>
#include <uuv_control_msgs/BottomSearchResponse.h>


namespace uuv_control_msgs
{

struct BottomSearch
{

typedef BottomSearchRequest Request;
typedef BottomSearchResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct BottomSearch
} // namespace uuv_control_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::uuv_control_msgs::BottomSearch > {
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::uuv_control_msgs::BottomSearch&) { return value(); }
};

template<>
struct DataType< ::uuv_control_msgs::BottomSearch > {
  static const char* value()
  {
    return "uuv_control_msgs/BottomSearch";
  }

  static const char* value(const ::uuv_control_msgs::BottomSearch&) { return value(); }
};


// service_traits::MD5Sum< ::uuv_control_msgs::BottomSearchRequest> should match
// service_traits::MD5Sum< ::uuv_control_msgs::BottomSearch >
template<>
struct MD5Sum< ::uuv_control_msgs::BottomSearchRequest>
{
  static const char* value()
  {
    return MD5Sum< ::uuv_control_msgs::BottomSearch >::value();
  }
  static const char* value(const ::uuv_control_msgs::BottomSearchRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::uuv_control_msgs::BottomSearchRequest> should match
// service_traits::DataType< ::uuv_control_msgs::BottomSearch >
template<>
struct DataType< ::uuv_control_msgs::BottomSearchRequest>
{
  static const char* value()
  {
    return DataType< ::uuv_control_msgs::BottomSearch >::value();
  }
  static const char* value(const ::uuv_control_msgs::BottomSearchRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::uuv_control_msgs::BottomSearchResponse> should match
// service_traits::MD5Sum< ::uuv_control_msgs::BottomSearch >
template<>
struct MD5Sum< ::uuv_control_msgs::BottomSearchResponse>
{
  static const char* value()
  {
    return MD5Sum< ::uuv_control_msgs::BottomSearch >::value();
  }
  static const char* value(const ::uuv_control_msgs::BottomSearchResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::uuv_control_msgs::BottomSearchResponse> should match
// service_traits::DataType< ::uuv_control_msgs::BottomSearch >
template<>
struct DataType< ::uuv_control_msgs::BottomSearchResponse>
{
  static const char* value()
  {
    return DataType< ::uuv_control_msgs::BottomSearch >::value();
  }
  static const char* value(const ::uuv_control_msgs::BottomSearchResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UUV_CONTROL_MSGS_MESSAGE_BOTTOMSEARCH_H
