// Generated by gencpp from file uuv_control_msgs/CancelRequest.msg
// DO NOT EDIT!


#ifndef UUV_CONTROL_MSGS_MESSAGE_CANCELREQUEST_H
#define UUV_CONTROL_MSGS_MESSAGE_CANCELREQUEST_H

#include <ros/service_traits.h>


#include <uuv_control_msgs/CancelRequestRequest.h>
#include <uuv_control_msgs/CancelRequestResponse.h>


namespace uuv_control_msgs
{

struct CancelRequest
{

typedef CancelRequestRequest Request;
typedef CancelRequestResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CancelRequest
} // namespace uuv_control_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::uuv_control_msgs::CancelRequest > {
  static const char* value()
  {
    return "5a9276df2b28afacd9f38505f03ae185";
  }

  static const char* value(const ::uuv_control_msgs::CancelRequest&) { return value(); }
};

template<>
struct DataType< ::uuv_control_msgs::CancelRequest > {
  static const char* value()
  {
    return "uuv_control_msgs/CancelRequest";
  }

  static const char* value(const ::uuv_control_msgs::CancelRequest&) { return value(); }
};


// service_traits::MD5Sum< ::uuv_control_msgs::CancelRequestRequest> should match
// service_traits::MD5Sum< ::uuv_control_msgs::CancelRequest >
template<>
struct MD5Sum< ::uuv_control_msgs::CancelRequestRequest>
{
  static const char* value()
  {
    return MD5Sum< ::uuv_control_msgs::CancelRequest >::value();
  }
  static const char* value(const ::uuv_control_msgs::CancelRequestRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::uuv_control_msgs::CancelRequestRequest> should match
// service_traits::DataType< ::uuv_control_msgs::CancelRequest >
template<>
struct DataType< ::uuv_control_msgs::CancelRequestRequest>
{
  static const char* value()
  {
    return DataType< ::uuv_control_msgs::CancelRequest >::value();
  }
  static const char* value(const ::uuv_control_msgs::CancelRequestRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::uuv_control_msgs::CancelRequestResponse> should match
// service_traits::MD5Sum< ::uuv_control_msgs::CancelRequest >
template<>
struct MD5Sum< ::uuv_control_msgs::CancelRequestResponse>
{
  static const char* value()
  {
    return MD5Sum< ::uuv_control_msgs::CancelRequest >::value();
  }
  static const char* value(const ::uuv_control_msgs::CancelRequestResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::uuv_control_msgs::CancelRequestResponse> should match
// service_traits::DataType< ::uuv_control_msgs::CancelRequest >
template<>
struct DataType< ::uuv_control_msgs::CancelRequestResponse>
{
  static const char* value()
  {
    return DataType< ::uuv_control_msgs::CancelRequest >::value();
  }
  static const char* value(const ::uuv_control_msgs::CancelRequestResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UUV_CONTROL_MSGS_MESSAGE_CANCELREQUEST_H
