// Auto-generated. Do not edit!

// (in-package motion_layer.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class pitchPIDFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.current_pitch = null;
    }
    else {
      if (initObj.hasOwnProperty('current_pitch')) {
        this.current_pitch = initObj.current_pitch
      }
      else {
        this.current_pitch = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type pitchPIDFeedback
    // Serialize message field [current_pitch]
    bufferOffset = _serializer.float32(obj.current_pitch, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type pitchPIDFeedback
    let len;
    let data = new pitchPIDFeedback(null);
    // Deserialize message field [current_pitch]
    data.current_pitch = _deserializer.float32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'motion_layer/pitchPIDFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '4a3adda3d08a8fafdac976fb1d309ab9';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #feedback
    float32 current_pitch
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new pitchPIDFeedback(null);
    if (msg.current_pitch !== undefined) {
      resolved.current_pitch = msg.current_pitch;
    }
    else {
      resolved.current_pitch = 0.0
    }

    return resolved;
    }
};

module.exports = pitchPIDFeedback;
