// Auto-generated. Do not edit!

// (in-package motion_layer.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class rollPIDGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.target_roll = null;
    }
    else {
      if (initObj.hasOwnProperty('target_roll')) {
        this.target_roll = initObj.target_roll
      }
      else {
        this.target_roll = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type rollPIDGoal
    // Serialize message field [target_roll]
    bufferOffset = _serializer.float32(obj.target_roll, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type rollPIDGoal
    let len;
    let data = new rollPIDGoal(null);
    // Deserialize message field [target_roll]
    data.target_roll = _deserializer.float32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'motion_layer/rollPIDGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '8579d0d5acecc338d88fe61d8a460d00';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #goal definition
    float32 target_roll
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new rollPIDGoal(null);
    if (msg.target_roll !== undefined) {
      resolved.target_roll = msg.target_roll;
    }
    else {
      resolved.target_roll = 0.0
    }

    return resolved;
    }
};

module.exports = rollPIDGoal;
