// Auto-generated. Do not edit!

// (in-package motion_layer.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class surgePIDGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.target_surge = null;
    }
    else {
      if (initObj.hasOwnProperty('target_surge')) {
        this.target_surge = initObj.target_surge
      }
      else {
        this.target_surge = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type surgePIDGoal
    // Serialize message field [target_surge]
    bufferOffset = _serializer.float32(obj.target_surge, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type surgePIDGoal
    let len;
    let data = new surgePIDGoal(null);
    // Deserialize message field [target_surge]
    data.target_surge = _deserializer.float32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'motion_layer/surgePIDGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'c048d1b60602754426604d629608fbb4';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #goal definition
    float32 target_surge
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new surgePIDGoal(null);
    if (msg.target_surge !== undefined) {
      resolved.target_surge = msg.target_surge;
    }
    else {
      resolved.target_surge = 0.0
    }

    return resolved;
    }
};

module.exports = surgePIDGoal;
