// Auto-generated. Do not edit!

// (in-package motion_layer.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class swayPIDResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.final_sway = null;
    }
    else {
      if (initObj.hasOwnProperty('final_sway')) {
        this.final_sway = initObj.final_sway
      }
      else {
        this.final_sway = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type swayPIDResult
    // Serialize message field [final_sway]
    bufferOffset = _serializer.float32(obj.final_sway, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type swayPIDResult
    let len;
    let data = new swayPIDResult(null);
    // Deserialize message field [final_sway]
    data.final_sway = _deserializer.float32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'motion_layer/swayPIDResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'caf532cf86e6945e76412b977b45a0ad';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #result definition
    float32 final_sway
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new swayPIDResult(null);
    if (msg.final_sway !== undefined) {
      resolved.final_sway = msg.final_sway;
    }
    else {
      resolved.final_sway = 0.0
    }

    return resolved;
    }
};

module.exports = swayPIDResult;
