// Auto-generated. Do not edit!

// (in-package motion_layer.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class swayPIDFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.current_sway = null;
    }
    else {
      if (initObj.hasOwnProperty('current_sway')) {
        this.current_sway = initObj.current_sway
      }
      else {
        this.current_sway = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type swayPIDFeedback
    // Serialize message field [current_sway]
    bufferOffset = _serializer.float32(obj.current_sway, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type swayPIDFeedback
    let len;
    let data = new swayPIDFeedback(null);
    // Deserialize message field [current_sway]
    data.current_sway = _deserializer.float32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'motion_layer/swayPIDFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'be329fdf096e22ff88e07cdc485b51bb';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #feedback
    float32 current_sway
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new swayPIDFeedback(null);
    if (msg.current_sway !== undefined) {
      resolved.current_sway = msg.current_sway;
    }
    else {
      resolved.current_sway = 0.0
    }

    return resolved;
    }
};

module.exports = swayPIDFeedback;
