// Auto-generated. Do not edit!

// (in-package motion_layer.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class yawPIDFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.current_yaw = null;
    }
    else {
      if (initObj.hasOwnProperty('current_yaw')) {
        this.current_yaw = initObj.current_yaw
      }
      else {
        this.current_yaw = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type yawPIDFeedback
    // Serialize message field [current_yaw]
    bufferOffset = _serializer.float32(obj.current_yaw, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type yawPIDFeedback
    let len;
    let data = new yawPIDFeedback(null);
    // Deserialize message field [current_yaw]
    data.current_yaw = _deserializer.float32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'motion_layer/yawPIDFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '5426ab92bfb888eb685e27deaa84cea8';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #feedback
    float32 current_yaw
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new yawPIDFeedback(null);
    if (msg.current_yaw !== undefined) {
      resolved.current_yaw = msg.current_yaw;
    }
    else {
      resolved.current_yaw = 0.0
    }

    return resolved;
    }
};

module.exports = yawPIDFeedback;
