// Generated by gencpp from file mapping/slam_srv.msg
// DO NOT EDIT!


#ifndef MAPPING_MESSAGE_SLAM_SRV_H
#define MAPPING_MESSAGE_SLAM_SRV_H

#include <ros/service_traits.h>


#include <mapping/slam_srvRequest.h>
#include <mapping/slam_srvResponse.h>


namespace mapping
{

struct slam_srv
{

typedef slam_srvRequest Request;
typedef slam_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct slam_srv
} // namespace mapping


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mapping::slam_srv > {
  static const char* value()
  {
    return "848707f5ade96d3dc60ab7ec14c58f27";
  }

  static const char* value(const ::mapping::slam_srv&) { return value(); }
};

template<>
struct DataType< ::mapping::slam_srv > {
  static const char* value()
  {
    return "mapping/slam_srv";
  }

  static const char* value(const ::mapping::slam_srv&) { return value(); }
};


// service_traits::MD5Sum< ::mapping::slam_srvRequest> should match
// service_traits::MD5Sum< ::mapping::slam_srv >
template<>
struct MD5Sum< ::mapping::slam_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mapping::slam_srv >::value();
  }
  static const char* value(const ::mapping::slam_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mapping::slam_srvRequest> should match
// service_traits::DataType< ::mapping::slam_srv >
template<>
struct DataType< ::mapping::slam_srvRequest>
{
  static const char* value()
  {
    return DataType< ::mapping::slam_srv >::value();
  }
  static const char* value(const ::mapping::slam_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mapping::slam_srvResponse> should match
// service_traits::MD5Sum< ::mapping::slam_srv >
template<>
struct MD5Sum< ::mapping::slam_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mapping::slam_srv >::value();
  }
  static const char* value(const ::mapping::slam_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mapping::slam_srvResponse> should match
// service_traits::DataType< ::mapping::slam_srv >
template<>
struct DataType< ::mapping::slam_srvResponse>
{
  static const char* value()
  {
    return DataType< ::mapping::slam_srv >::value();
  }
  static const char* value(const ::mapping::slam_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAPPING_MESSAGE_SLAM_SRV_H
