// Generated by gencpp from file mapping/slam_srvResponse.msg
// DO NOT EDIT!


#ifndef MAPPING_MESSAGE_SLAM_SRVRESPONSE_H
#define MAPPING_MESSAGE_SLAM_SRVRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mapping
{
template <class ContainerAllocator>
struct slam_srvResponse_
{
  typedef slam_srvResponse_<ContainerAllocator> Type;

  slam_srvResponse_()
    : m_x(0.0)
    , m_y(0.0)
    , m_z(0.0)
    , u_x(0.0)
    , u_y(0.0)
    , u_z(0.0)  {
    }
  slam_srvResponse_(const ContainerAllocator& _alloc)
    : m_x(0.0)
    , m_y(0.0)
    , m_z(0.0)
    , u_x(0.0)
    , u_y(0.0)
    , u_z(0.0)  {
  (void)_alloc;
    }



   typedef float _m_x_type;
  _m_x_type m_x;

   typedef float _m_y_type;
  _m_y_type m_y;

   typedef float _m_z_type;
  _m_z_type m_z;

   typedef float _u_x_type;
  _u_x_type u_x;

   typedef float _u_y_type;
  _u_y_type u_y;

   typedef float _u_z_type;
  _u_z_type u_z;





  typedef boost::shared_ptr< ::mapping::slam_srvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mapping::slam_srvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct slam_srvResponse_

typedef ::mapping::slam_srvResponse_<std::allocator<void> > slam_srvResponse;

typedef boost::shared_ptr< ::mapping::slam_srvResponse > slam_srvResponsePtr;
typedef boost::shared_ptr< ::mapping::slam_srvResponse const> slam_srvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mapping::slam_srvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mapping::slam_srvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mapping::slam_srvResponse_<ContainerAllocator1> & lhs, const ::mapping::slam_srvResponse_<ContainerAllocator2> & rhs)
{
  return lhs.m_x == rhs.m_x &&
    lhs.m_y == rhs.m_y &&
    lhs.m_z == rhs.m_z &&
    lhs.u_x == rhs.u_x &&
    lhs.u_y == rhs.u_y &&
    lhs.u_z == rhs.u_z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mapping::slam_srvResponse_<ContainerAllocator1> & lhs, const ::mapping::slam_srvResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mapping

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::mapping::slam_srvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mapping::slam_srvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mapping::slam_srvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mapping::slam_srvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mapping::slam_srvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mapping::slam_srvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mapping::slam_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d78dd65d3ae653252ce84040bdfe18f7";
  }

  static const char* value(const ::mapping::slam_srvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd78dd65d3ae65325ULL;
  static const uint64_t static_value2 = 0x2ce84040bdfe18f7ULL;
};

template<class ContainerAllocator>
struct DataType< ::mapping::slam_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mapping/slam_srvResponse";
  }

  static const char* value(const ::mapping::slam_srvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mapping::slam_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 m_x\n"
"float32 m_y\n"
"float32 m_z\n"
"float32 u_x\n"
"float32 u_y\n"
"float32 u_z\n"
;
  }

  static const char* value(const ::mapping::slam_srvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mapping::slam_srvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.m_x);
      stream.next(m.m_y);
      stream.next(m.m_z);
      stream.next(m.u_x);
      stream.next(m.u_y);
      stream.next(m.u_z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct slam_srvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mapping::slam_srvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mapping::slam_srvResponse_<ContainerAllocator>& v)
  {
    s << indent << "m_x: ";
    Printer<float>::stream(s, indent + "  ", v.m_x);
    s << indent << "m_y: ";
    Printer<float>::stream(s, indent + "  ", v.m_y);
    s << indent << "m_z: ";
    Printer<float>::stream(s, indent + "  ", v.m_z);
    s << indent << "u_x: ";
    Printer<float>::stream(s, indent + "  ", v.u_x);
    s << indent << "u_y: ";
    Printer<float>::stream(s, indent + "  ", v.u_y);
    s << indent << "u_z: ";
    Printer<float>::stream(s, indent + "  ", v.u_z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAPPING_MESSAGE_SLAM_SRVRESPONSE_H
