; Auto-generated. Do not edit!


(cl:in-package motion_layer-msg)


;//! \htmlinclude pitchPIDGoal.msg.html

(cl:defclass <pitchPIDGoal> (roslisp-msg-protocol:ros-message)
  ((target_pitch
    :reader target_pitch
    :initarg :target_pitch
    :type cl:float
    :initform 0.0))
)

(cl:defclass pitchPIDGoal (<pitchPIDGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <pitchPIDGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'pitchPIDGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name motion_layer-msg:<pitchPIDGoal> is deprecated: use motion_layer-msg:pitchPIDGoal instead.")))

(cl:ensure-generic-function 'target_pitch-val :lambda-list '(m))
(cl:defmethod target_pitch-val ((m <pitchPIDGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader motion_layer-msg:target_pitch-val is deprecated.  Use motion_layer-msg:target_pitch instead.")
  (target_pitch m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <pitchPIDGoal>) ostream)
  "Serializes a message object of type '<pitchPIDGoal>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'target_pitch))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <pitchPIDGoal>) istream)
  "Deserializes a message object of type '<pitchPIDGoal>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'target_pitch) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<pitchPIDGoal>)))
  "Returns string type for a message object of type '<pitchPIDGoal>"
  "motion_layer/pitchPIDGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'pitchPIDGoal)))
  "Returns string type for a message object of type 'pitchPIDGoal"
  "motion_layer/pitchPIDGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<pitchPIDGoal>)))
  "Returns md5sum for a message object of type '<pitchPIDGoal>"
  "ec0b683a317c75858db233efbba002eb")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'pitchPIDGoal)))
  "Returns md5sum for a message object of type 'pitchPIDGoal"
  "ec0b683a317c75858db233efbba002eb")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<pitchPIDGoal>)))
  "Returns full string definition for message of type '<pitchPIDGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%float32 target_pitch~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'pitchPIDGoal)))
  "Returns full string definition for message of type 'pitchPIDGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%float32 target_pitch~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <pitchPIDGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <pitchPIDGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'pitchPIDGoal
    (cl:cons ':target_pitch (target_pitch msg))
))
