; Auto-generated. Do not edit!


(cl:in-package motion_layer-msg)


;//! \htmlinclude pitchPIDResult.msg.html

(cl:defclass <pitchPIDResult> (roslisp-msg-protocol:ros-message)
  ((final_pitch
    :reader final_pitch
    :initarg :final_pitch
    :type cl:float
    :initform 0.0))
)

(cl:defclass pitchPIDResult (<pitchPIDResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <pitchPIDResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'pitchPIDResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name motion_layer-msg:<pitchPIDResult> is deprecated: use motion_layer-msg:pitchPIDResult instead.")))

(cl:ensure-generic-function 'final_pitch-val :lambda-list '(m))
(cl:defmethod final_pitch-val ((m <pitchPIDResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader motion_layer-msg:final_pitch-val is deprecated.  Use motion_layer-msg:final_pitch instead.")
  (final_pitch m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <pitchPIDResult>) ostream)
  "Serializes a message object of type '<pitchPIDResult>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'final_pitch))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <pitchPIDResult>) istream)
  "Deserializes a message object of type '<pitchPIDResult>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'final_pitch) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<pitchPIDResult>)))
  "Returns string type for a message object of type '<pitchPIDResult>"
  "motion_layer/pitchPIDResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'pitchPIDResult)))
  "Returns string type for a message object of type 'pitchPIDResult"
  "motion_layer/pitchPIDResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<pitchPIDResult>)))
  "Returns md5sum for a message object of type '<pitchPIDResult>"
  "023d6e0d38c16492952462da3f10ef90")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'pitchPIDResult)))
  "Returns md5sum for a message object of type 'pitchPIDResult"
  "023d6e0d38c16492952462da3f10ef90")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<pitchPIDResult>)))
  "Returns full string definition for message of type '<pitchPIDResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%float32 final_pitch~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'pitchPIDResult)))
  "Returns full string definition for message of type 'pitchPIDResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%float32 final_pitch~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <pitchPIDResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <pitchPIDResult>))
  "Converts a ROS message object to a list"
  (cl:list 'pitchPIDResult
    (cl:cons ':final_pitch (final_pitch msg))
))
