; Auto-generated. Do not edit!


(cl:in-package motion_layer-msg)


;//! \htmlinclude surgePIDFeedback.msg.html

(cl:defclass <surgePIDFeedback> (roslisp-msg-protocol:ros-message)
  ((current_surge
    :reader current_surge
    :initarg :current_surge
    :type cl:float
    :initform 0.0))
)

(cl:defclass surgePIDFeedback (<surgePIDFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <surgePIDFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'surgePIDFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name motion_layer-msg:<surgePIDFeedback> is deprecated: use motion_layer-msg:surgePIDFeedback instead.")))

(cl:ensure-generic-function 'current_surge-val :lambda-list '(m))
(cl:defmethod current_surge-val ((m <surgePIDFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader motion_layer-msg:current_surge-val is deprecated.  Use motion_layer-msg:current_surge instead.")
  (current_surge m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <surgePIDFeedback>) ostream)
  "Serializes a message object of type '<surgePIDFeedback>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'current_surge))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <surgePIDFeedback>) istream)
  "Deserializes a message object of type '<surgePIDFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'current_surge) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<surgePIDFeedback>)))
  "Returns string type for a message object of type '<surgePIDFeedback>"
  "motion_layer/surgePIDFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'surgePIDFeedback)))
  "Returns string type for a message object of type 'surgePIDFeedback"
  "motion_layer/surgePIDFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<surgePIDFeedback>)))
  "Returns md5sum for a message object of type '<surgePIDFeedback>"
  "2f4f09cc6277c7b8bac0e0c58e06e505")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'surgePIDFeedback)))
  "Returns md5sum for a message object of type 'surgePIDFeedback"
  "2f4f09cc6277c7b8bac0e0c58e06e505")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<surgePIDFeedback>)))
  "Returns full string definition for message of type '<surgePIDFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%float32 current_surge~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'surgePIDFeedback)))
  "Returns full string definition for message of type 'surgePIDFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%float32 current_surge~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <surgePIDFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <surgePIDFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'surgePIDFeedback
    (cl:cons ':current_surge (current_surge msg))
))
