; Auto-generated. Do not edit!


(cl:in-package motion_layer-msg)


;//! \htmlinclude swayPIDFeedback.msg.html

(cl:defclass <swayPIDFeedback> (roslisp-msg-protocol:ros-message)
  ((current_sway
    :reader current_sway
    :initarg :current_sway
    :type cl:float
    :initform 0.0))
)

(cl:defclass swayPIDFeedback (<swayPIDFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <swayPIDFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'swayPIDFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name motion_layer-msg:<swayPIDFeedback> is deprecated: use motion_layer-msg:swayPIDFeedback instead.")))

(cl:ensure-generic-function 'current_sway-val :lambda-list '(m))
(cl:defmethod current_sway-val ((m <swayPIDFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader motion_layer-msg:current_sway-val is deprecated.  Use motion_layer-msg:current_sway instead.")
  (current_sway m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <swayPIDFeedback>) ostream)
  "Serializes a message object of type '<swayPIDFeedback>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'current_sway))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <swayPIDFeedback>) istream)
  "Deserializes a message object of type '<swayPIDFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'current_sway) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<swayPIDFeedback>)))
  "Returns string type for a message object of type '<swayPIDFeedback>"
  "motion_layer/swayPIDFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'swayPIDFeedback)))
  "Returns string type for a message object of type 'swayPIDFeedback"
  "motion_layer/swayPIDFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<swayPIDFeedback>)))
  "Returns md5sum for a message object of type '<swayPIDFeedback>"
  "be329fdf096e22ff88e07cdc485b51bb")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'swayPIDFeedback)))
  "Returns md5sum for a message object of type 'swayPIDFeedback"
  "be329fdf096e22ff88e07cdc485b51bb")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<swayPIDFeedback>)))
  "Returns full string definition for message of type '<swayPIDFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%float32 current_sway~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'swayPIDFeedback)))
  "Returns full string definition for message of type 'swayPIDFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%float32 current_sway~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <swayPIDFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <swayPIDFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'swayPIDFeedback
    (cl:cons ':current_sway (current_sway msg))
))
