; Auto-generated. Do not edit!


(cl:in-package motion_layer-msg)


;//! \htmlinclude swayPIDResult.msg.html

(cl:defclass <swayPIDResult> (roslisp-msg-protocol:ros-message)
  ((final_sway
    :reader final_sway
    :initarg :final_sway
    :type cl:float
    :initform 0.0))
)

(cl:defclass swayPIDResult (<swayPIDResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <swayPIDResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'swayPIDResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name motion_layer-msg:<swayPIDResult> is deprecated: use motion_layer-msg:swayPIDResult instead.")))

(cl:ensure-generic-function 'final_sway-val :lambda-list '(m))
(cl:defmethod final_sway-val ((m <swayPIDResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader motion_layer-msg:final_sway-val is deprecated.  Use motion_layer-msg:final_sway instead.")
  (final_sway m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <swayPIDResult>) ostream)
  "Serializes a message object of type '<swayPIDResult>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'final_sway))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <swayPIDResult>) istream)
  "Deserializes a message object of type '<swayPIDResult>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'final_sway) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<swayPIDResult>)))
  "Returns string type for a message object of type '<swayPIDResult>"
  "motion_layer/swayPIDResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'swayPIDResult)))
  "Returns string type for a message object of type 'swayPIDResult"
  "motion_layer/swayPIDResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<swayPIDResult>)))
  "Returns md5sum for a message object of type '<swayPIDResult>"
  "caf532cf86e6945e76412b977b45a0ad")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'swayPIDResult)))
  "Returns md5sum for a message object of type 'swayPIDResult"
  "caf532cf86e6945e76412b977b45a0ad")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<swayPIDResult>)))
  "Returns full string definition for message of type '<swayPIDResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%float32 final_sway~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'swayPIDResult)))
  "Returns full string definition for message of type 'swayPIDResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%float32 final_sway~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <swayPIDResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <swayPIDResult>))
  "Converts a ROS message object to a list"
  (cl:list 'swayPIDResult
    (cl:cons ':final_sway (final_sway msg))
))
