; Auto-generated. Do not edit!


(cl:in-package motion_layer-msg)


;//! \htmlinclude yawPIDGoal.msg.html

(cl:defclass <yawPIDGoal> (roslisp-msg-protocol:ros-message)
  ((target_yaw
    :reader target_yaw
    :initarg :target_yaw
    :type cl:float
    :initform 0.0))
)

(cl:defclass yawPIDGoal (<yawPIDGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <yawPIDGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'yawPIDGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name motion_layer-msg:<yawPIDGoal> is deprecated: use motion_layer-msg:yawPIDGoal instead.")))

(cl:ensure-generic-function 'target_yaw-val :lambda-list '(m))
(cl:defmethod target_yaw-val ((m <yawPIDGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader motion_layer-msg:target_yaw-val is deprecated.  Use motion_layer-msg:target_yaw instead.")
  (target_yaw m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <yawPIDGoal>) ostream)
  "Serializes a message object of type '<yawPIDGoal>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'target_yaw))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <yawPIDGoal>) istream)
  "Deserializes a message object of type '<yawPIDGoal>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'target_yaw) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<yawPIDGoal>)))
  "Returns string type for a message object of type '<yawPIDGoal>"
  "motion_layer/yawPIDGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'yawPIDGoal)))
  "Returns string type for a message object of type 'yawPIDGoal"
  "motion_layer/yawPIDGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<yawPIDGoal>)))
  "Returns md5sum for a message object of type '<yawPIDGoal>"
  "9b22a33e1e2d10b44c75e6d648c9882f")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'yawPIDGoal)))
  "Returns md5sum for a message object of type 'yawPIDGoal"
  "9b22a33e1e2d10b44c75e6d648c9882f")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<yawPIDGoal>)))
  "Returns full string definition for message of type '<yawPIDGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%float32 target_yaw~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'yawPIDGoal)))
  "Returns full string definition for message of type 'yawPIDGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%float32 target_yaw~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <yawPIDGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <yawPIDGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'yawPIDGoal
    (cl:cons ':target_yaw (target_yaw msg))
))
