// Generated by gencpp from file color_calibration/Dump.msg
// DO NOT EDIT!


#ifndef COLOR_CALIBRATION_MESSAGE_DUMP_H
#define COLOR_CALIBRATION_MESSAGE_DUMP_H

#include <ros/service_traits.h>


#include <color_calibration/DumpRequest.h>
#include <color_calibration/DumpResponse.h>


namespace color_calibration
{

struct Dump
{

typedef DumpRequest Request;
typedef DumpResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Dump
} // namespace color_calibration


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::color_calibration::Dump > {
  static const char* value()
  {
    return "1ffe68613b014a3d042297d0d1a5d021";
  }

  static const char* value(const ::color_calibration::Dump&) { return value(); }
};

template<>
struct DataType< ::color_calibration::Dump > {
  static const char* value()
  {
    return "color_calibration/Dump";
  }

  static const char* value(const ::color_calibration::Dump&) { return value(); }
};


// service_traits::MD5Sum< ::color_calibration::DumpRequest> should match
// service_traits::MD5Sum< ::color_calibration::Dump >
template<>
struct MD5Sum< ::color_calibration::DumpRequest>
{
  static const char* value()
  {
    return MD5Sum< ::color_calibration::Dump >::value();
  }
  static const char* value(const ::color_calibration::DumpRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::color_calibration::DumpRequest> should match
// service_traits::DataType< ::color_calibration::Dump >
template<>
struct DataType< ::color_calibration::DumpRequest>
{
  static const char* value()
  {
    return DataType< ::color_calibration::Dump >::value();
  }
  static const char* value(const ::color_calibration::DumpRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::color_calibration::DumpResponse> should match
// service_traits::MD5Sum< ::color_calibration::Dump >
template<>
struct MD5Sum< ::color_calibration::DumpResponse>
{
  static const char* value()
  {
    return MD5Sum< ::color_calibration::Dump >::value();
  }
  static const char* value(const ::color_calibration::DumpResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::color_calibration::DumpResponse> should match
// service_traits::DataType< ::color_calibration::Dump >
template<>
struct DataType< ::color_calibration::DumpResponse>
{
  static const char* value()
  {
    return DataType< ::color_calibration::Dump >::value();
  }
  static const char* value(const ::color_calibration::DumpResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COLOR_CALIBRATION_MESSAGE_DUMP_H
