// Generated by gencpp from file color_calibration/DumpResponse.msg
// DO NOT EDIT!


#ifndef COLOR_CALIBRATION_MESSAGE_DUMPRESPONSE_H
#define COLOR_CALIBRATION_MESSAGE_DUMPRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace color_calibration
{
template <class ContainerAllocator>
struct DumpResponse_
{
  typedef DumpResponse_<ContainerAllocator> Type;

  DumpResponse_()
    : status(false)  {
    }
  DumpResponse_(const ContainerAllocator& _alloc)
    : status(false)  {
  (void)_alloc;
    }



   typedef uint8_t _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::color_calibration::DumpResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::color_calibration::DumpResponse_<ContainerAllocator> const> ConstPtr;

}; // struct DumpResponse_

typedef ::color_calibration::DumpResponse_<std::allocator<void> > DumpResponse;

typedef boost::shared_ptr< ::color_calibration::DumpResponse > DumpResponsePtr;
typedef boost::shared_ptr< ::color_calibration::DumpResponse const> DumpResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::color_calibration::DumpResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::color_calibration::DumpResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::color_calibration::DumpResponse_<ContainerAllocator1> & lhs, const ::color_calibration::DumpResponse_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::color_calibration::DumpResponse_<ContainerAllocator1> & lhs, const ::color_calibration::DumpResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace color_calibration

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::color_calibration::DumpResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::color_calibration::DumpResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::color_calibration::DumpResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::color_calibration::DumpResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::color_calibration::DumpResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::color_calibration::DumpResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::color_calibration::DumpResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3a1255d4d998bd4d6585c64639b5ee9a";
  }

  static const char* value(const ::color_calibration::DumpResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3a1255d4d998bd4dULL;
  static const uint64_t static_value2 = 0x6585c64639b5ee9aULL;
};

template<class ContainerAllocator>
struct DataType< ::color_calibration::DumpResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "color_calibration/DumpResponse";
  }

  static const char* value(const ::color_calibration::DumpResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::color_calibration::DumpResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool status\n"
;
  }

  static const char* value(const ::color_calibration::DumpResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::color_calibration::DumpResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DumpResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::color_calibration::DumpResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::color_calibration::DumpResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COLOR_CALIBRATION_MESSAGE_DUMPRESPONSE_H
