// Generated by gencpp from file xsens_driver/ResetIMUOrientRequest.msg
// DO NOT EDIT!


#ifndef XSENS_DRIVER_MESSAGE_RESETIMUORIENTREQUEST_H
#define XSENS_DRIVER_MESSAGE_RESETIMUORIENTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace xsens_driver
{
template <class ContainerAllocator>
struct ResetIMUOrientRequest_
{
  typedef ResetIMUOrientRequest_<ContainerAllocator> Type;

  ResetIMUOrientRequest_()
    {
    }
  ResetIMUOrientRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::xsens_driver::ResetIMUOrientRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::xsens_driver::ResetIMUOrientRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ResetIMUOrientRequest_

typedef ::xsens_driver::ResetIMUOrientRequest_<std::allocator<void> > ResetIMUOrientRequest;

typedef boost::shared_ptr< ::xsens_driver::ResetIMUOrientRequest > ResetIMUOrientRequestPtr;
typedef boost::shared_ptr< ::xsens_driver::ResetIMUOrientRequest const> ResetIMUOrientRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::xsens_driver::ResetIMUOrientRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::xsens_driver::ResetIMUOrientRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace xsens_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::xsens_driver::ResetIMUOrientRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xsens_driver::ResetIMUOrientRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xsens_driver::ResetIMUOrientRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xsens_driver::ResetIMUOrientRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xsens_driver::ResetIMUOrientRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xsens_driver::ResetIMUOrientRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::xsens_driver::ResetIMUOrientRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::xsens_driver::ResetIMUOrientRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::xsens_driver::ResetIMUOrientRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "xsens_driver/ResetIMUOrientRequest";
  }

  static const char* value(const ::xsens_driver::ResetIMUOrientRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::xsens_driver::ResetIMUOrientRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This service is used for resetting the current orientation as [0,0,0,1]\n"
;
  }

  static const char* value(const ::xsens_driver::ResetIMUOrientRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::xsens_driver::ResetIMUOrientRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ResetIMUOrientRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::xsens_driver::ResetIMUOrientRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::xsens_driver::ResetIMUOrientRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // XSENS_DRIVER_MESSAGE_RESETIMUORIENTREQUEST_H
