// Generated by gencpp from file xsens_driver/ResetIMUOrient.msg
// DO NOT EDIT!


#ifndef XSENS_DRIVER_MESSAGE_RESETIMUORIENT_H
#define XSENS_DRIVER_MESSAGE_RESETIMUORIENT_H

#include <ros/service_traits.h>


#include <xsens_driver/ResetIMUOrientRequest.h>
#include <xsens_driver/ResetIMUOrientResponse.h>


namespace xsens_driver
{

struct ResetIMUOrient
{

typedef ResetIMUOrientRequest Request;
typedef ResetIMUOrientResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ResetIMUOrient
} // namespace xsens_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::xsens_driver::ResetIMUOrient > {
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::xsens_driver::ResetIMUOrient&) { return value(); }
};

template<>
struct DataType< ::xsens_driver::ResetIMUOrient > {
  static const char* value()
  {
    return "xsens_driver/ResetIMUOrient";
  }

  static const char* value(const ::xsens_driver::ResetIMUOrient&) { return value(); }
};


// service_traits::MD5Sum< ::xsens_driver::ResetIMUOrientRequest> should match
// service_traits::MD5Sum< ::xsens_driver::ResetIMUOrient >
template<>
struct MD5Sum< ::xsens_driver::ResetIMUOrientRequest>
{
  static const char* value()
  {
    return MD5Sum< ::xsens_driver::ResetIMUOrient >::value();
  }
  static const char* value(const ::xsens_driver::ResetIMUOrientRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::xsens_driver::ResetIMUOrientRequest> should match
// service_traits::DataType< ::xsens_driver::ResetIMUOrient >
template<>
struct DataType< ::xsens_driver::ResetIMUOrientRequest>
{
  static const char* value()
  {
    return DataType< ::xsens_driver::ResetIMUOrient >::value();
  }
  static const char* value(const ::xsens_driver::ResetIMUOrientRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::xsens_driver::ResetIMUOrientResponse> should match
// service_traits::MD5Sum< ::xsens_driver::ResetIMUOrient >
template<>
struct MD5Sum< ::xsens_driver::ResetIMUOrientResponse>
{
  static const char* value()
  {
    return MD5Sum< ::xsens_driver::ResetIMUOrient >::value();
  }
  static const char* value(const ::xsens_driver::ResetIMUOrientResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::xsens_driver::ResetIMUOrientResponse> should match
// service_traits::DataType< ::xsens_driver::ResetIMUOrient >
template<>
struct DataType< ::xsens_driver::ResetIMUOrientResponse>
{
  static const char* value()
  {
    return DataType< ::xsens_driver::ResetIMUOrient >::value();
  }
  static const char* value(const ::xsens_driver::ResetIMUOrientResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // XSENS_DRIVER_MESSAGE_RESETIMUORIENT_H
