(cl:defpackage odom_dvl_imu-srv
  (:use )
  (:export
   "SETDEPTHOFFSET"
   "<SETDEPTHOFFSET-REQUEST>"
   "SETDEPTHOFFSET-REQUEST"
   "<SETDEPTHOFFSET-RESPONSE>"
   "SETDEPTHOFFSET-RESPONSE"
   "SETWORLDXYOFFSET"
   "<SETWORLDXYOFFSET-REQUEST>"
   "SETWORLDXYOFFSET-REQUEST"
   "<SETWORLDXYOFFSET-RESPONSE>"
   "SETWORLDXYOFFSET-RESPONSE"
  ))

