// Generated by gencpp from file motion_layer/heavePIDGoal.msg
// DO NOT EDIT!


#ifndef MOTION_LAYER_MESSAGE_HEAVEPIDGOAL_H
#define MOTION_LAYER_MESSAGE_HEAVEPIDGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace motion_layer
{
template <class ContainerAllocator>
struct heavePIDGoal_
{
  typedef heavePIDGoal_<ContainerAllocator> Type;

  heavePIDGoal_()
    : target_heave(0.0)  {
    }
  heavePIDGoal_(const ContainerAllocator& _alloc)
    : target_heave(0.0)  {
  (void)_alloc;
    }



   typedef float _target_heave_type;
  _target_heave_type target_heave;





  typedef boost::shared_ptr< ::motion_layer::heavePIDGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motion_layer::heavePIDGoal_<ContainerAllocator> const> ConstPtr;

}; // struct heavePIDGoal_

typedef ::motion_layer::heavePIDGoal_<std::allocator<void> > heavePIDGoal;

typedef boost::shared_ptr< ::motion_layer::heavePIDGoal > heavePIDGoalPtr;
typedef boost::shared_ptr< ::motion_layer::heavePIDGoal const> heavePIDGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motion_layer::heavePIDGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motion_layer::heavePIDGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::motion_layer::heavePIDGoal_<ContainerAllocator1> & lhs, const ::motion_layer::heavePIDGoal_<ContainerAllocator2> & rhs)
{
  return lhs.target_heave == rhs.target_heave;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::motion_layer::heavePIDGoal_<ContainerAllocator1> & lhs, const ::motion_layer::heavePIDGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace motion_layer

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::motion_layer::heavePIDGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motion_layer::heavePIDGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motion_layer::heavePIDGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motion_layer::heavePIDGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motion_layer::heavePIDGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motion_layer::heavePIDGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motion_layer::heavePIDGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e3e0196b6c96119284595cf4c2ac78a5";
  }

  static const char* value(const ::motion_layer::heavePIDGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe3e0196b6c961192ULL;
  static const uint64_t static_value2 = 0x84595cf4c2ac78a5ULL;
};

template<class ContainerAllocator>
struct DataType< ::motion_layer::heavePIDGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motion_layer/heavePIDGoal";
  }

  static const char* value(const ::motion_layer::heavePIDGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motion_layer::heavePIDGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#goal definition\n"
"float32 target_heave\n"
;
  }

  static const char* value(const ::motion_layer::heavePIDGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motion_layer::heavePIDGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.target_heave);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct heavePIDGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motion_layer::heavePIDGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motion_layer::heavePIDGoal_<ContainerAllocator>& v)
  {
    s << indent << "target_heave: ";
    Printer<float>::stream(s, indent + "  ", v.target_heave);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTION_LAYER_MESSAGE_HEAVEPIDGOAL_H
