// Generated by gencpp from file motion_layer/heavePIDResult.msg
// DO NOT EDIT!


#ifndef MOTION_LAYER_MESSAGE_HEAVEPIDRESULT_H
#define MOTION_LAYER_MESSAGE_HEAVEPIDRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace motion_layer
{
template <class ContainerAllocator>
struct heavePIDResult_
{
  typedef heavePIDResult_<ContainerAllocator> Type;

  heavePIDResult_()
    : final_heave(0.0)  {
    }
  heavePIDResult_(const ContainerAllocator& _alloc)
    : final_heave(0.0)  {
  (void)_alloc;
    }



   typedef float _final_heave_type;
  _final_heave_type final_heave;





  typedef boost::shared_ptr< ::motion_layer::heavePIDResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motion_layer::heavePIDResult_<ContainerAllocator> const> ConstPtr;

}; // struct heavePIDResult_

typedef ::motion_layer::heavePIDResult_<std::allocator<void> > heavePIDResult;

typedef boost::shared_ptr< ::motion_layer::heavePIDResult > heavePIDResultPtr;
typedef boost::shared_ptr< ::motion_layer::heavePIDResult const> heavePIDResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motion_layer::heavePIDResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motion_layer::heavePIDResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::motion_layer::heavePIDResult_<ContainerAllocator1> & lhs, const ::motion_layer::heavePIDResult_<ContainerAllocator2> & rhs)
{
  return lhs.final_heave == rhs.final_heave;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::motion_layer::heavePIDResult_<ContainerAllocator1> & lhs, const ::motion_layer::heavePIDResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace motion_layer

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::motion_layer::heavePIDResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motion_layer::heavePIDResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motion_layer::heavePIDResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motion_layer::heavePIDResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motion_layer::heavePIDResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motion_layer::heavePIDResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motion_layer::heavePIDResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2b06543602cb26dc881723c9f2f50b97";
  }

  static const char* value(const ::motion_layer::heavePIDResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2b06543602cb26dcULL;
  static const uint64_t static_value2 = 0x881723c9f2f50b97ULL;
};

template<class ContainerAllocator>
struct DataType< ::motion_layer::heavePIDResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motion_layer/heavePIDResult";
  }

  static const char* value(const ::motion_layer::heavePIDResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motion_layer::heavePIDResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#result definition\n"
"float32 final_heave\n"
;
  }

  static const char* value(const ::motion_layer::heavePIDResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motion_layer::heavePIDResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.final_heave);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct heavePIDResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motion_layer::heavePIDResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motion_layer::heavePIDResult_<ContainerAllocator>& v)
  {
    s << indent << "final_heave: ";
    Printer<float>::stream(s, indent + "  ", v.final_heave);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTION_LAYER_MESSAGE_HEAVEPIDRESULT_H
