// Generated by gencpp from file motion_layer/pitchPIDResult.msg
// DO NOT EDIT!


#ifndef MOTION_LAYER_MESSAGE_PITCHPIDRESULT_H
#define MOTION_LAYER_MESSAGE_PITCHPIDRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace motion_layer
{
template <class ContainerAllocator>
struct pitchPIDResult_
{
  typedef pitchPIDResult_<ContainerAllocator> Type;

  pitchPIDResult_()
    : final_pitch(0.0)  {
    }
  pitchPIDResult_(const ContainerAllocator& _alloc)
    : final_pitch(0.0)  {
  (void)_alloc;
    }



   typedef float _final_pitch_type;
  _final_pitch_type final_pitch;





  typedef boost::shared_ptr< ::motion_layer::pitchPIDResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motion_layer::pitchPIDResult_<ContainerAllocator> const> ConstPtr;

}; // struct pitchPIDResult_

typedef ::motion_layer::pitchPIDResult_<std::allocator<void> > pitchPIDResult;

typedef boost::shared_ptr< ::motion_layer::pitchPIDResult > pitchPIDResultPtr;
typedef boost::shared_ptr< ::motion_layer::pitchPIDResult const> pitchPIDResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motion_layer::pitchPIDResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motion_layer::pitchPIDResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::motion_layer::pitchPIDResult_<ContainerAllocator1> & lhs, const ::motion_layer::pitchPIDResult_<ContainerAllocator2> & rhs)
{
  return lhs.final_pitch == rhs.final_pitch;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::motion_layer::pitchPIDResult_<ContainerAllocator1> & lhs, const ::motion_layer::pitchPIDResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace motion_layer

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::motion_layer::pitchPIDResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motion_layer::pitchPIDResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motion_layer::pitchPIDResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motion_layer::pitchPIDResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motion_layer::pitchPIDResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motion_layer::pitchPIDResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motion_layer::pitchPIDResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "023d6e0d38c16492952462da3f10ef90";
  }

  static const char* value(const ::motion_layer::pitchPIDResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x023d6e0d38c16492ULL;
  static const uint64_t static_value2 = 0x952462da3f10ef90ULL;
};

template<class ContainerAllocator>
struct DataType< ::motion_layer::pitchPIDResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motion_layer/pitchPIDResult";
  }

  static const char* value(const ::motion_layer::pitchPIDResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motion_layer::pitchPIDResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#result definition\n"
"float32 final_pitch\n"
;
  }

  static const char* value(const ::motion_layer::pitchPIDResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motion_layer::pitchPIDResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.final_pitch);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pitchPIDResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motion_layer::pitchPIDResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motion_layer::pitchPIDResult_<ContainerAllocator>& v)
  {
    s << indent << "final_pitch: ";
    Printer<float>::stream(s, indent + "  ", v.final_pitch);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTION_LAYER_MESSAGE_PITCHPIDRESULT_H
