// Generated by gencpp from file motion_layer/rollPIDFeedback.msg
// DO NOT EDIT!


#ifndef MOTION_LAYER_MESSAGE_ROLLPIDFEEDBACK_H
#define MOTION_LAYER_MESSAGE_ROLLPIDFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace motion_layer
{
template <class ContainerAllocator>
struct rollPIDFeedback_
{
  typedef rollPIDFeedback_<ContainerAllocator> Type;

  rollPIDFeedback_()
    : current_roll(0.0)  {
    }
  rollPIDFeedback_(const ContainerAllocator& _alloc)
    : current_roll(0.0)  {
  (void)_alloc;
    }



   typedef float _current_roll_type;
  _current_roll_type current_roll;





  typedef boost::shared_ptr< ::motion_layer::rollPIDFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motion_layer::rollPIDFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct rollPIDFeedback_

typedef ::motion_layer::rollPIDFeedback_<std::allocator<void> > rollPIDFeedback;

typedef boost::shared_ptr< ::motion_layer::rollPIDFeedback > rollPIDFeedbackPtr;
typedef boost::shared_ptr< ::motion_layer::rollPIDFeedback const> rollPIDFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motion_layer::rollPIDFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motion_layer::rollPIDFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::motion_layer::rollPIDFeedback_<ContainerAllocator1> & lhs, const ::motion_layer::rollPIDFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.current_roll == rhs.current_roll;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::motion_layer::rollPIDFeedback_<ContainerAllocator1> & lhs, const ::motion_layer::rollPIDFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace motion_layer

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::motion_layer::rollPIDFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motion_layer::rollPIDFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motion_layer::rollPIDFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motion_layer::rollPIDFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motion_layer::rollPIDFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motion_layer::rollPIDFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motion_layer::rollPIDFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0b1c3bb55f73ee21b48520acf40dcb7f";
  }

  static const char* value(const ::motion_layer::rollPIDFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0b1c3bb55f73ee21ULL;
  static const uint64_t static_value2 = 0xb48520acf40dcb7fULL;
};

template<class ContainerAllocator>
struct DataType< ::motion_layer::rollPIDFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motion_layer/rollPIDFeedback";
  }

  static const char* value(const ::motion_layer::rollPIDFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motion_layer::rollPIDFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#feedback\n"
"float32 current_roll\n"
"\n"
;
  }

  static const char* value(const ::motion_layer::rollPIDFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motion_layer::rollPIDFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.current_roll);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct rollPIDFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motion_layer::rollPIDFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motion_layer::rollPIDFeedback_<ContainerAllocator>& v)
  {
    s << indent << "current_roll: ";
    Printer<float>::stream(s, indent + "  ", v.current_roll);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTION_LAYER_MESSAGE_ROLLPIDFEEDBACK_H
