// Generated by gencpp from file motion_layer/surgePIDFeedback.msg
// DO NOT EDIT!


#ifndef MOTION_LAYER_MESSAGE_SURGEPIDFEEDBACK_H
#define MOTION_LAYER_MESSAGE_SURGEPIDFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace motion_layer
{
template <class ContainerAllocator>
struct surgePIDFeedback_
{
  typedef surgePIDFeedback_<ContainerAllocator> Type;

  surgePIDFeedback_()
    : current_surge(0.0)  {
    }
  surgePIDFeedback_(const ContainerAllocator& _alloc)
    : current_surge(0.0)  {
  (void)_alloc;
    }



   typedef float _current_surge_type;
  _current_surge_type current_surge;





  typedef boost::shared_ptr< ::motion_layer::surgePIDFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motion_layer::surgePIDFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct surgePIDFeedback_

typedef ::motion_layer::surgePIDFeedback_<std::allocator<void> > surgePIDFeedback;

typedef boost::shared_ptr< ::motion_layer::surgePIDFeedback > surgePIDFeedbackPtr;
typedef boost::shared_ptr< ::motion_layer::surgePIDFeedback const> surgePIDFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motion_layer::surgePIDFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motion_layer::surgePIDFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::motion_layer::surgePIDFeedback_<ContainerAllocator1> & lhs, const ::motion_layer::surgePIDFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.current_surge == rhs.current_surge;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::motion_layer::surgePIDFeedback_<ContainerAllocator1> & lhs, const ::motion_layer::surgePIDFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace motion_layer

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::motion_layer::surgePIDFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motion_layer::surgePIDFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motion_layer::surgePIDFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motion_layer::surgePIDFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motion_layer::surgePIDFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motion_layer::surgePIDFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motion_layer::surgePIDFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2f4f09cc6277c7b8bac0e0c58e06e505";
  }

  static const char* value(const ::motion_layer::surgePIDFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2f4f09cc6277c7b8ULL;
  static const uint64_t static_value2 = 0xbac0e0c58e06e505ULL;
};

template<class ContainerAllocator>
struct DataType< ::motion_layer::surgePIDFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motion_layer/surgePIDFeedback";
  }

  static const char* value(const ::motion_layer::surgePIDFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motion_layer::surgePIDFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#feedback\n"
"float32 current_surge\n"
;
  }

  static const char* value(const ::motion_layer::surgePIDFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motion_layer::surgePIDFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.current_surge);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct surgePIDFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motion_layer::surgePIDFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motion_layer::surgePIDFeedback_<ContainerAllocator>& v)
  {
    s << indent << "current_surge: ";
    Printer<float>::stream(s, indent + "  ", v.current_surge);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTION_LAYER_MESSAGE_SURGEPIDFEEDBACK_H
