// Generated by gencpp from file motion_layer/yawPIDFeedback.msg
// DO NOT EDIT!


#ifndef MOTION_LAYER_MESSAGE_YAWPIDFEEDBACK_H
#define MOTION_LAYER_MESSAGE_YAWPIDFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace motion_layer
{
template <class ContainerAllocator>
struct yawPIDFeedback_
{
  typedef yawPIDFeedback_<ContainerAllocator> Type;

  yawPIDFeedback_()
    : current_yaw(0.0)  {
    }
  yawPIDFeedback_(const ContainerAllocator& _alloc)
    : current_yaw(0.0)  {
  (void)_alloc;
    }



   typedef float _current_yaw_type;
  _current_yaw_type current_yaw;





  typedef boost::shared_ptr< ::motion_layer::yawPIDFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motion_layer::yawPIDFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct yawPIDFeedback_

typedef ::motion_layer::yawPIDFeedback_<std::allocator<void> > yawPIDFeedback;

typedef boost::shared_ptr< ::motion_layer::yawPIDFeedback > yawPIDFeedbackPtr;
typedef boost::shared_ptr< ::motion_layer::yawPIDFeedback const> yawPIDFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motion_layer::yawPIDFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motion_layer::yawPIDFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::motion_layer::yawPIDFeedback_<ContainerAllocator1> & lhs, const ::motion_layer::yawPIDFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.current_yaw == rhs.current_yaw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::motion_layer::yawPIDFeedback_<ContainerAllocator1> & lhs, const ::motion_layer::yawPIDFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace motion_layer

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::motion_layer::yawPIDFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motion_layer::yawPIDFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motion_layer::yawPIDFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motion_layer::yawPIDFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motion_layer::yawPIDFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motion_layer::yawPIDFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motion_layer::yawPIDFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5426ab92bfb888eb685e27deaa84cea8";
  }

  static const char* value(const ::motion_layer::yawPIDFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5426ab92bfb888ebULL;
  static const uint64_t static_value2 = 0x685e27deaa84cea8ULL;
};

template<class ContainerAllocator>
struct DataType< ::motion_layer::yawPIDFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motion_layer/yawPIDFeedback";
  }

  static const char* value(const ::motion_layer::yawPIDFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motion_layer::yawPIDFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#feedback\n"
"float32 current_yaw\n"
;
  }

  static const char* value(const ::motion_layer::yawPIDFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motion_layer::yawPIDFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.current_yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct yawPIDFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motion_layer::yawPIDFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motion_layer::yawPIDFeedback_<ContainerAllocator>& v)
  {
    s << indent << "current_yaw: ";
    Printer<float>::stream(s, indent + "  ", v.current_yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTION_LAYER_MESSAGE_YAWPIDFEEDBACK_H
