// Generated by gencpp from file motion_layer/yawPIDGoal.msg
// DO NOT EDIT!


#ifndef MOTION_LAYER_MESSAGE_YAWPIDGOAL_H
#define MOTION_LAYER_MESSAGE_YAWPIDGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace motion_layer
{
template <class ContainerAllocator>
struct yawPIDGoal_
{
  typedef yawPIDGoal_<ContainerAllocator> Type;

  yawPIDGoal_()
    : target_yaw(0.0)  {
    }
  yawPIDGoal_(const ContainerAllocator& _alloc)
    : target_yaw(0.0)  {
  (void)_alloc;
    }



   typedef float _target_yaw_type;
  _target_yaw_type target_yaw;





  typedef boost::shared_ptr< ::motion_layer::yawPIDGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motion_layer::yawPIDGoal_<ContainerAllocator> const> ConstPtr;

}; // struct yawPIDGoal_

typedef ::motion_layer::yawPIDGoal_<std::allocator<void> > yawPIDGoal;

typedef boost::shared_ptr< ::motion_layer::yawPIDGoal > yawPIDGoalPtr;
typedef boost::shared_ptr< ::motion_layer::yawPIDGoal const> yawPIDGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motion_layer::yawPIDGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motion_layer::yawPIDGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::motion_layer::yawPIDGoal_<ContainerAllocator1> & lhs, const ::motion_layer::yawPIDGoal_<ContainerAllocator2> & rhs)
{
  return lhs.target_yaw == rhs.target_yaw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::motion_layer::yawPIDGoal_<ContainerAllocator1> & lhs, const ::motion_layer::yawPIDGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace motion_layer

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::motion_layer::yawPIDGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motion_layer::yawPIDGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motion_layer::yawPIDGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motion_layer::yawPIDGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motion_layer::yawPIDGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motion_layer::yawPIDGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motion_layer::yawPIDGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9b22a33e1e2d10b44c75e6d648c9882f";
  }

  static const char* value(const ::motion_layer::yawPIDGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9b22a33e1e2d10b4ULL;
  static const uint64_t static_value2 = 0x4c75e6d648c9882fULL;
};

template<class ContainerAllocator>
struct DataType< ::motion_layer::yawPIDGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motion_layer/yawPIDGoal";
  }

  static const char* value(const ::motion_layer::yawPIDGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motion_layer::yawPIDGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#goal definition\n"
"float32 target_yaw\n"
;
  }

  static const char* value(const ::motion_layer::yawPIDGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motion_layer::yawPIDGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.target_yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct yawPIDGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motion_layer::yawPIDGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motion_layer::yawPIDGoal_<ContainerAllocator>& v)
  {
    s << indent << "target_yaw: ";
    Printer<float>::stream(s, indent + "  ", v.target_yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTION_LAYER_MESSAGE_YAWPIDGOAL_H
