// Generated by gencpp from file master_layer/ChangeOdomRequest.msg
// DO NOT EDIT!


#ifndef MASTER_LAYER_MESSAGE_CHANGEODOMREQUEST_H
#define MASTER_LAYER_MESSAGE_CHANGEODOMREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace master_layer
{
template <class ContainerAllocator>
struct ChangeOdomRequest_
{
  typedef ChangeOdomRequest_<ContainerAllocator> Type;

  ChangeOdomRequest_()
    : odom()  {
    }
  ChangeOdomRequest_(const ContainerAllocator& _alloc)
    : odom(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _odom_type;
  _odom_type odom;





  typedef boost::shared_ptr< ::master_layer::ChangeOdomRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::master_layer::ChangeOdomRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ChangeOdomRequest_

typedef ::master_layer::ChangeOdomRequest_<std::allocator<void> > ChangeOdomRequest;

typedef boost::shared_ptr< ::master_layer::ChangeOdomRequest > ChangeOdomRequestPtr;
typedef boost::shared_ptr< ::master_layer::ChangeOdomRequest const> ChangeOdomRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::master_layer::ChangeOdomRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::master_layer::ChangeOdomRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::master_layer::ChangeOdomRequest_<ContainerAllocator1> & lhs, const ::master_layer::ChangeOdomRequest_<ContainerAllocator2> & rhs)
{
  return lhs.odom == rhs.odom;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::master_layer::ChangeOdomRequest_<ContainerAllocator1> & lhs, const ::master_layer::ChangeOdomRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace master_layer

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::master_layer::ChangeOdomRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::master_layer::ChangeOdomRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::master_layer::ChangeOdomRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::master_layer::ChangeOdomRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::master_layer::ChangeOdomRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::master_layer::ChangeOdomRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::master_layer::ChangeOdomRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2a526d3ba0c7c3651e14cda1880db1c3";
  }

  static const char* value(const ::master_layer::ChangeOdomRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2a526d3ba0c7c365ULL;
  static const uint64_t static_value2 = 0x1e14cda1880db1c3ULL;
};

template<class ContainerAllocator>
struct DataType< ::master_layer::ChangeOdomRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "master_layer/ChangeOdomRequest";
  }

  static const char* value(const ::master_layer::ChangeOdomRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::master_layer::ChangeOdomRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string odom\n"
;
  }

  static const char* value(const ::master_layer::ChangeOdomRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::master_layer::ChangeOdomRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.odom);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ChangeOdomRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::master_layer::ChangeOdomRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::master_layer::ChangeOdomRequest_<ContainerAllocator>& v)
  {
    s << indent << "odom: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.odom);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MASTER_LAYER_MESSAGE_CHANGEODOMREQUEST_H
