// Generated by gencpp from file master_layer/ChangeOdom.msg
// DO NOT EDIT!


#ifndef MASTER_LAYER_MESSAGE_CHANGEODOM_H
#define MASTER_LAYER_MESSAGE_CHANGEODOM_H

#include <ros/service_traits.h>


#include <master_layer/ChangeOdomRequest.h>
#include <master_layer/ChangeOdomResponse.h>


namespace master_layer
{

struct ChangeOdom
{

typedef ChangeOdomRequest Request;
typedef ChangeOdomResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ChangeOdom
} // namespace master_layer


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::master_layer::ChangeOdom > {
  static const char* value()
  {
    return "a13c647c475c61dc7ffb9a19071ada11";
  }

  static const char* value(const ::master_layer::ChangeOdom&) { return value(); }
};

template<>
struct DataType< ::master_layer::ChangeOdom > {
  static const char* value()
  {
    return "master_layer/ChangeOdom";
  }

  static const char* value(const ::master_layer::ChangeOdom&) { return value(); }
};


// service_traits::MD5Sum< ::master_layer::ChangeOdomRequest> should match
// service_traits::MD5Sum< ::master_layer::ChangeOdom >
template<>
struct MD5Sum< ::master_layer::ChangeOdomRequest>
{
  static const char* value()
  {
    return MD5Sum< ::master_layer::ChangeOdom >::value();
  }
  static const char* value(const ::master_layer::ChangeOdomRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::master_layer::ChangeOdomRequest> should match
// service_traits::DataType< ::master_layer::ChangeOdom >
template<>
struct DataType< ::master_layer::ChangeOdomRequest>
{
  static const char* value()
  {
    return DataType< ::master_layer::ChangeOdom >::value();
  }
  static const char* value(const ::master_layer::ChangeOdomRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::master_layer::ChangeOdomResponse> should match
// service_traits::MD5Sum< ::master_layer::ChangeOdom >
template<>
struct MD5Sum< ::master_layer::ChangeOdomResponse>
{
  static const char* value()
  {
    return MD5Sum< ::master_layer::ChangeOdom >::value();
  }
  static const char* value(const ::master_layer::ChangeOdomResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::master_layer::ChangeOdomResponse> should match
// service_traits::DataType< ::master_layer::ChangeOdom >
template<>
struct DataType< ::master_layer::ChangeOdomResponse>
{
  static const char* value()
  {
    return DataType< ::master_layer::ChangeOdom >::value();
  }
  static const char* value(const ::master_layer::ChangeOdomResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MASTER_LAYER_MESSAGE_CHANGEODOM_H
