// Generated by gencpp from file master_layer/GetBlackoutTime.msg
// DO NOT EDIT!


#ifndef MASTER_LAYER_MESSAGE_GETBLACKOUTTIME_H
#define MASTER_LAYER_MESSAGE_GETBLACKOUTTIME_H

#include <ros/service_traits.h>


#include <master_layer/GetBlackoutTimeRequest.h>
#include <master_layer/GetBlackoutTimeResponse.h>


namespace master_layer
{

struct GetBlackoutTime
{

typedef GetBlackoutTimeRequest Request;
typedef GetBlackoutTimeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetBlackoutTime
} // namespace master_layer


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::master_layer::GetBlackoutTime > {
  static const char* value()
  {
    return "a29e3fd05b552a0ff08fadbb66286b1a";
  }

  static const char* value(const ::master_layer::GetBlackoutTime&) { return value(); }
};

template<>
struct DataType< ::master_layer::GetBlackoutTime > {
  static const char* value()
  {
    return "master_layer/GetBlackoutTime";
  }

  static const char* value(const ::master_layer::GetBlackoutTime&) { return value(); }
};


// service_traits::MD5Sum< ::master_layer::GetBlackoutTimeRequest> should match
// service_traits::MD5Sum< ::master_layer::GetBlackoutTime >
template<>
struct MD5Sum< ::master_layer::GetBlackoutTimeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::master_layer::GetBlackoutTime >::value();
  }
  static const char* value(const ::master_layer::GetBlackoutTimeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::master_layer::GetBlackoutTimeRequest> should match
// service_traits::DataType< ::master_layer::GetBlackoutTime >
template<>
struct DataType< ::master_layer::GetBlackoutTimeRequest>
{
  static const char* value()
  {
    return DataType< ::master_layer::GetBlackoutTime >::value();
  }
  static const char* value(const ::master_layer::GetBlackoutTimeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::master_layer::GetBlackoutTimeResponse> should match
// service_traits::MD5Sum< ::master_layer::GetBlackoutTime >
template<>
struct MD5Sum< ::master_layer::GetBlackoutTimeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::master_layer::GetBlackoutTime >::value();
  }
  static const char* value(const ::master_layer::GetBlackoutTimeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::master_layer::GetBlackoutTimeResponse> should match
// service_traits::DataType< ::master_layer::GetBlackoutTime >
template<>
struct DataType< ::master_layer::GetBlackoutTimeResponse>
{
  static const char* value()
  {
    return DataType< ::master_layer::GetBlackoutTime >::value();
  }
  static const char* value(const ::master_layer::GetBlackoutTimeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MASTER_LAYER_MESSAGE_GETBLACKOUTTIME_H
