// Generated by gencpp from file master_layer/GetMaxDepthResponse.msg
// DO NOT EDIT!


#ifndef MASTER_LAYER_MESSAGE_GETMAXDEPTHRESPONSE_H
#define MASTER_LAYER_MESSAGE_GETMAXDEPTHRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace master_layer
{
template <class ContainerAllocator>
struct GetMaxDepthResponse_
{
  typedef GetMaxDepthResponse_<ContainerAllocator> Type;

  GetMaxDepthResponse_()
    : depth(0.0)  {
    }
  GetMaxDepthResponse_(const ContainerAllocator& _alloc)
    : depth(0.0)  {
  (void)_alloc;
    }



   typedef float _depth_type;
  _depth_type depth;





  typedef boost::shared_ptr< ::master_layer::GetMaxDepthResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::master_layer::GetMaxDepthResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetMaxDepthResponse_

typedef ::master_layer::GetMaxDepthResponse_<std::allocator<void> > GetMaxDepthResponse;

typedef boost::shared_ptr< ::master_layer::GetMaxDepthResponse > GetMaxDepthResponsePtr;
typedef boost::shared_ptr< ::master_layer::GetMaxDepthResponse const> GetMaxDepthResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::master_layer::GetMaxDepthResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::master_layer::GetMaxDepthResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::master_layer::GetMaxDepthResponse_<ContainerAllocator1> & lhs, const ::master_layer::GetMaxDepthResponse_<ContainerAllocator2> & rhs)
{
  return lhs.depth == rhs.depth;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::master_layer::GetMaxDepthResponse_<ContainerAllocator1> & lhs, const ::master_layer::GetMaxDepthResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace master_layer

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::master_layer::GetMaxDepthResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::master_layer::GetMaxDepthResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::master_layer::GetMaxDepthResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::master_layer::GetMaxDepthResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::master_layer::GetMaxDepthResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::master_layer::GetMaxDepthResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::master_layer::GetMaxDepthResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6deb06b7b7183f5581b3362a0cb413b7";
  }

  static const char* value(const ::master_layer::GetMaxDepthResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6deb06b7b7183f55ULL;
  static const uint64_t static_value2 = 0x81b3362a0cb413b7ULL;
};

template<class ContainerAllocator>
struct DataType< ::master_layer::GetMaxDepthResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "master_layer/GetMaxDepthResponse";
  }

  static const char* value(const ::master_layer::GetMaxDepthResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::master_layer::GetMaxDepthResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 depth\n"
;
  }

  static const char* value(const ::master_layer::GetMaxDepthResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::master_layer::GetMaxDepthResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.depth);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetMaxDepthResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::master_layer::GetMaxDepthResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::master_layer::GetMaxDepthResponse_<ContainerAllocator>& v)
  {
    s << indent << "depth: ";
    Printer<float>::stream(s, indent + "  ", v.depth);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MASTER_LAYER_MESSAGE_GETMAXDEPTHRESPONSE_H
