// Generated by gencpp from file master_layer/GetMaxDepth.msg
// DO NOT EDIT!


#ifndef MASTER_LAYER_MESSAGE_GETMAXDEPTH_H
#define MASTER_LAYER_MESSAGE_GETMAXDEPTH_H

#include <ros/service_traits.h>


#include <master_layer/GetMaxDepthRequest.h>
#include <master_layer/GetMaxDepthResponse.h>


namespace master_layer
{

struct GetMaxDepth
{

typedef GetMaxDepthRequest Request;
typedef GetMaxDepthResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetMaxDepth
} // namespace master_layer


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::master_layer::GetMaxDepth > {
  static const char* value()
  {
    return "6deb06b7b7183f5581b3362a0cb413b7";
  }

  static const char* value(const ::master_layer::GetMaxDepth&) { return value(); }
};

template<>
struct DataType< ::master_layer::GetMaxDepth > {
  static const char* value()
  {
    return "master_layer/GetMaxDepth";
  }

  static const char* value(const ::master_layer::GetMaxDepth&) { return value(); }
};


// service_traits::MD5Sum< ::master_layer::GetMaxDepthRequest> should match
// service_traits::MD5Sum< ::master_layer::GetMaxDepth >
template<>
struct MD5Sum< ::master_layer::GetMaxDepthRequest>
{
  static const char* value()
  {
    return MD5Sum< ::master_layer::GetMaxDepth >::value();
  }
  static const char* value(const ::master_layer::GetMaxDepthRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::master_layer::GetMaxDepthRequest> should match
// service_traits::DataType< ::master_layer::GetMaxDepth >
template<>
struct DataType< ::master_layer::GetMaxDepthRequest>
{
  static const char* value()
  {
    return DataType< ::master_layer::GetMaxDepth >::value();
  }
  static const char* value(const ::master_layer::GetMaxDepthRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::master_layer::GetMaxDepthResponse> should match
// service_traits::MD5Sum< ::master_layer::GetMaxDepth >
template<>
struct MD5Sum< ::master_layer::GetMaxDepthResponse>
{
  static const char* value()
  {
    return MD5Sum< ::master_layer::GetMaxDepth >::value();
  }
  static const char* value(const ::master_layer::GetMaxDepthResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::master_layer::GetMaxDepthResponse> should match
// service_traits::DataType< ::master_layer::GetMaxDepth >
template<>
struct DataType< ::master_layer::GetMaxDepthResponse>
{
  static const char* value()
  {
    return DataType< ::master_layer::GetMaxDepth >::value();
  }
  static const char* value(const ::master_layer::GetMaxDepthResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MASTER_LAYER_MESSAGE_GETMAXDEPTH_H
