// Generated by gencpp from file master_layer/GoToPose.msg
// DO NOT EDIT!


#ifndef MASTER_LAYER_MESSAGE_GOTOPOSE_H
#define MASTER_LAYER_MESSAGE_GOTOPOSE_H

#include <ros/service_traits.h>


#include <master_layer/GoToPoseRequest.h>
#include <master_layer/GoToPoseResponse.h>


namespace master_layer
{

struct GoToPose
{

typedef GoToPoseRequest Request;
typedef GoToPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GoToPose
} // namespace master_layer


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::master_layer::GoToPose > {
  static const char* value()
  {
    return "fca097bf97be1a76fa923cfcb956b244";
  }

  static const char* value(const ::master_layer::GoToPose&) { return value(); }
};

template<>
struct DataType< ::master_layer::GoToPose > {
  static const char* value()
  {
    return "master_layer/GoToPose";
  }

  static const char* value(const ::master_layer::GoToPose&) { return value(); }
};


// service_traits::MD5Sum< ::master_layer::GoToPoseRequest> should match
// service_traits::MD5Sum< ::master_layer::GoToPose >
template<>
struct MD5Sum< ::master_layer::GoToPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::master_layer::GoToPose >::value();
  }
  static const char* value(const ::master_layer::GoToPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::master_layer::GoToPoseRequest> should match
// service_traits::DataType< ::master_layer::GoToPose >
template<>
struct DataType< ::master_layer::GoToPoseRequest>
{
  static const char* value()
  {
    return DataType< ::master_layer::GoToPose >::value();
  }
  static const char* value(const ::master_layer::GoToPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::master_layer::GoToPoseResponse> should match
// service_traits::MD5Sum< ::master_layer::GoToPose >
template<>
struct MD5Sum< ::master_layer::GoToPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::master_layer::GoToPose >::value();
  }
  static const char* value(const ::master_layer::GoToPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::master_layer::GoToPoseResponse> should match
// service_traits::DataType< ::master_layer::GoToPose >
template<>
struct DataType< ::master_layer::GoToPoseResponse>
{
  static const char* value()
  {
    return DataType< ::master_layer::GoToPose >::value();
  }
  static const char* value(const ::master_layer::GoToPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MASTER_LAYER_MESSAGE_GOTOPOSE_H
