// Generated by gencpp from file master_layer/GoToIncrementalRequest.msg
// DO NOT EDIT!


#ifndef MASTER_LAYER_MESSAGE_GOTOINCREMENTALREQUEST_H
#define MASTER_LAYER_MESSAGE_GOTOINCREMENTALREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace master_layer
{
template <class ContainerAllocator>
struct GoToIncrementalRequest_
{
  typedef GoToIncrementalRequest_<ContainerAllocator> Type;

  GoToIncrementalRequest_()
    : step()
    , max_forward_speed(0.0)
    , interpolator()  {
    }
  GoToIncrementalRequest_(const ContainerAllocator& _alloc)
    : step(_alloc)
    , max_forward_speed(0.0)
    , interpolator(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _step_type;
  _step_type step;

   typedef double _max_forward_speed_type;
  _max_forward_speed_type max_forward_speed;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _interpolator_type;
  _interpolator_type interpolator;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(LIPB)
  #undef LIPB
#endif
#if defined(_WIN32) && defined(CUBIC)
  #undef CUBIC
#endif
#if defined(_WIN32) && defined(DUBINS)
  #undef DUBINS
#endif
#if defined(_WIN32) && defined(LINEAR)
  #undef LINEAR
#endif


  static const std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> LIPB;
  static const std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> CUBIC;
  static const std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> DUBINS;
  static const std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> LINEAR;

  typedef boost::shared_ptr< ::master_layer::GoToIncrementalRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::master_layer::GoToIncrementalRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GoToIncrementalRequest_

typedef ::master_layer::GoToIncrementalRequest_<std::allocator<void> > GoToIncrementalRequest;

typedef boost::shared_ptr< ::master_layer::GoToIncrementalRequest > GoToIncrementalRequestPtr;
typedef boost::shared_ptr< ::master_layer::GoToIncrementalRequest const> GoToIncrementalRequestConstPtr;

// constants requiring out of line definition

   
   template<typename ContainerAllocator> const std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>
      GoToIncrementalRequest_<ContainerAllocator>::LIPB =
        
          "'lipb'"
        
        ;
   

   
   template<typename ContainerAllocator> const std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>
      GoToIncrementalRequest_<ContainerAllocator>::CUBIC =
        
          "'cubic'"
        
        ;
   

   
   template<typename ContainerAllocator> const std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>
      GoToIncrementalRequest_<ContainerAllocator>::DUBINS =
        
          "'dubins'"
        
        ;
   

   
   template<typename ContainerAllocator> const std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>
      GoToIncrementalRequest_<ContainerAllocator>::LINEAR =
        
          "'linear'"
        
        ;
   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::master_layer::GoToIncrementalRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::master_layer::GoToIncrementalRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::master_layer::GoToIncrementalRequest_<ContainerAllocator1> & lhs, const ::master_layer::GoToIncrementalRequest_<ContainerAllocator2> & rhs)
{
  return lhs.step == rhs.step &&
    lhs.max_forward_speed == rhs.max_forward_speed &&
    lhs.interpolator == rhs.interpolator;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::master_layer::GoToIncrementalRequest_<ContainerAllocator1> & lhs, const ::master_layer::GoToIncrementalRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace master_layer

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::master_layer::GoToIncrementalRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::master_layer::GoToIncrementalRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::master_layer::GoToIncrementalRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::master_layer::GoToIncrementalRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::master_layer::GoToIncrementalRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::master_layer::GoToIncrementalRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::master_layer::GoToIncrementalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "83b72c3bd49f592c1f3511f3c61026e3";
  }

  static const char* value(const ::master_layer::GoToIncrementalRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x83b72c3bd49f592cULL;
  static const uint64_t static_value2 = 0x1f3511f3c61026e3ULL;
};

template<class ContainerAllocator>
struct DataType< ::master_layer::GoToIncrementalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "master_layer/GoToIncrementalRequest";
  }

  static const char* value(const ::master_layer::GoToIncrementalRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::master_layer::GoToIncrementalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string LIPB='lipb'\n"
"string CUBIC='cubic'\n"
"string DUBINS='dubins'\n"
"string LINEAR='linear'\n"
"\n"
"geometry_msgs/Point step\n"
"float64 max_forward_speed\n"
"string interpolator\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::master_layer::GoToIncrementalRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::master_layer::GoToIncrementalRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.step);
      stream.next(m.max_forward_speed);
      stream.next(m.interpolator);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GoToIncrementalRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::master_layer::GoToIncrementalRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::master_layer::GoToIncrementalRequest_<ContainerAllocator>& v)
  {
    s << indent << "step: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.step);
    s << indent << "max_forward_speed: ";
    Printer<double>::stream(s, indent + "  ", v.max_forward_speed);
    s << indent << "interpolator: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.interpolator);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MASTER_LAYER_MESSAGE_GOTOINCREMENTALREQUEST_H
