// Generated by gencpp from file master_layer/GoTo.msg
// DO NOT EDIT!


#ifndef MASTER_LAYER_MESSAGE_GOTO_H
#define MASTER_LAYER_MESSAGE_GOTO_H

#include <ros/service_traits.h>


#include <master_layer/GoToRequest.h>
#include <master_layer/GoToResponse.h>


namespace master_layer
{

struct GoTo
{

typedef GoToRequest Request;
typedef GoToResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GoTo
} // namespace master_layer


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::master_layer::GoTo > {
  static const char* value()
  {
    return "eb71f5d5260cbf8d35aafdcc7d71057c";
  }

  static const char* value(const ::master_layer::GoTo&) { return value(); }
};

template<>
struct DataType< ::master_layer::GoTo > {
  static const char* value()
  {
    return "master_layer/GoTo";
  }

  static const char* value(const ::master_layer::GoTo&) { return value(); }
};


// service_traits::MD5Sum< ::master_layer::GoToRequest> should match
// service_traits::MD5Sum< ::master_layer::GoTo >
template<>
struct MD5Sum< ::master_layer::GoToRequest>
{
  static const char* value()
  {
    return MD5Sum< ::master_layer::GoTo >::value();
  }
  static const char* value(const ::master_layer::GoToRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::master_layer::GoToRequest> should match
// service_traits::DataType< ::master_layer::GoTo >
template<>
struct DataType< ::master_layer::GoToRequest>
{
  static const char* value()
  {
    return DataType< ::master_layer::GoTo >::value();
  }
  static const char* value(const ::master_layer::GoToRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::master_layer::GoToResponse> should match
// service_traits::MD5Sum< ::master_layer::GoTo >
template<>
struct MD5Sum< ::master_layer::GoToResponse>
{
  static const char* value()
  {
    return MD5Sum< ::master_layer::GoTo >::value();
  }
  static const char* value(const ::master_layer::GoToResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::master_layer::GoToResponse> should match
// service_traits::DataType< ::master_layer::GoTo >
template<>
struct DataType< ::master_layer::GoToResponse>
{
  static const char* value()
  {
    return DataType< ::master_layer::GoTo >::value();
  }
  static const char* value(const ::master_layer::GoToResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MASTER_LAYER_MESSAGE_GOTO_H
