// Generated by gencpp from file master_layer/GoToIncremental.msg
// DO NOT EDIT!


#ifndef MASTER_LAYER_MESSAGE_GOTOINCREMENTAL_H
#define MASTER_LAYER_MESSAGE_GOTOINCREMENTAL_H

#include <ros/service_traits.h>


#include <master_layer/GoToIncrementalRequest.h>
#include <master_layer/GoToIncrementalResponse.h>


namespace master_layer
{

struct GoToIncremental
{

typedef GoToIncrementalRequest Request;
typedef GoToIncrementalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GoToIncremental
} // namespace master_layer


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::master_layer::GoToIncremental > {
  static const char* value()
  {
    return "ea062c779dd21cbac8fefabcd9b5f18e";
  }

  static const char* value(const ::master_layer::GoToIncremental&) { return value(); }
};

template<>
struct DataType< ::master_layer::GoToIncremental > {
  static const char* value()
  {
    return "master_layer/GoToIncremental";
  }

  static const char* value(const ::master_layer::GoToIncremental&) { return value(); }
};


// service_traits::MD5Sum< ::master_layer::GoToIncrementalRequest> should match
// service_traits::MD5Sum< ::master_layer::GoToIncremental >
template<>
struct MD5Sum< ::master_layer::GoToIncrementalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::master_layer::GoToIncremental >::value();
  }
  static const char* value(const ::master_layer::GoToIncrementalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::master_layer::GoToIncrementalRequest> should match
// service_traits::DataType< ::master_layer::GoToIncremental >
template<>
struct DataType< ::master_layer::GoToIncrementalRequest>
{
  static const char* value()
  {
    return DataType< ::master_layer::GoToIncremental >::value();
  }
  static const char* value(const ::master_layer::GoToIncrementalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::master_layer::GoToIncrementalResponse> should match
// service_traits::MD5Sum< ::master_layer::GoToIncremental >
template<>
struct MD5Sum< ::master_layer::GoToIncrementalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::master_layer::GoToIncremental >::value();
  }
  static const char* value(const ::master_layer::GoToIncrementalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::master_layer::GoToIncrementalResponse> should match
// service_traits::DataType< ::master_layer::GoToIncremental >
template<>
struct DataType< ::master_layer::GoToIncrementalResponse>
{
  static const char* value()
  {
    return DataType< ::master_layer::GoToIncremental >::value();
  }
  static const char* value(const ::master_layer::GoToIncrementalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MASTER_LAYER_MESSAGE_GOTOINCREMENTAL_H
