// Generated by gencpp from file master_layer/Hold.msg
// DO NOT EDIT!


#ifndef MASTER_LAYER_MESSAGE_HOLD_H
#define MASTER_LAYER_MESSAGE_HOLD_H

#include <ros/service_traits.h>


#include <master_layer/HoldRequest.h>
#include <master_layer/HoldResponse.h>


namespace master_layer
{

struct Hold
{

typedef HoldRequest Request;
typedef HoldResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Hold
} // namespace master_layer


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::master_layer::Hold > {
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::master_layer::Hold&) { return value(); }
};

template<>
struct DataType< ::master_layer::Hold > {
  static const char* value()
  {
    return "master_layer/Hold";
  }

  static const char* value(const ::master_layer::Hold&) { return value(); }
};


// service_traits::MD5Sum< ::master_layer::HoldRequest> should match
// service_traits::MD5Sum< ::master_layer::Hold >
template<>
struct MD5Sum< ::master_layer::HoldRequest>
{
  static const char* value()
  {
    return MD5Sum< ::master_layer::Hold >::value();
  }
  static const char* value(const ::master_layer::HoldRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::master_layer::HoldRequest> should match
// service_traits::DataType< ::master_layer::Hold >
template<>
struct DataType< ::master_layer::HoldRequest>
{
  static const char* value()
  {
    return DataType< ::master_layer::Hold >::value();
  }
  static const char* value(const ::master_layer::HoldRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::master_layer::HoldResponse> should match
// service_traits::MD5Sum< ::master_layer::Hold >
template<>
struct MD5Sum< ::master_layer::HoldResponse>
{
  static const char* value()
  {
    return MD5Sum< ::master_layer::Hold >::value();
  }
  static const char* value(const ::master_layer::HoldResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::master_layer::HoldResponse> should match
// service_traits::DataType< ::master_layer::Hold >
template<>
struct DataType< ::master_layer::HoldResponse>
{
  static const char* value()
  {
    return DataType< ::master_layer::Hold >::value();
  }
  static const char* value(const ::master_layer::HoldResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MASTER_LAYER_MESSAGE_HOLD_H
