// Generated by gencpp from file master_layer/InitCircularTrajectory.msg
// DO NOT EDIT!


#ifndef MASTER_LAYER_MESSAGE_INITCIRCULARTRAJECTORY_H
#define MASTER_LAYER_MESSAGE_INITCIRCULARTRAJECTORY_H

#include <ros/service_traits.h>


#include <master_layer/InitCircularTrajectoryRequest.h>
#include <master_layer/InitCircularTrajectoryResponse.h>


namespace master_layer
{

struct InitCircularTrajectory
{

typedef InitCircularTrajectoryRequest Request;
typedef InitCircularTrajectoryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct InitCircularTrajectory
} // namespace master_layer


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::master_layer::InitCircularTrajectory > {
  static const char* value()
  {
    return "4e2b6d8506f8a3b1f6ffe498d85ccc39";
  }

  static const char* value(const ::master_layer::InitCircularTrajectory&) { return value(); }
};

template<>
struct DataType< ::master_layer::InitCircularTrajectory > {
  static const char* value()
  {
    return "master_layer/InitCircularTrajectory";
  }

  static const char* value(const ::master_layer::InitCircularTrajectory&) { return value(); }
};


// service_traits::MD5Sum< ::master_layer::InitCircularTrajectoryRequest> should match
// service_traits::MD5Sum< ::master_layer::InitCircularTrajectory >
template<>
struct MD5Sum< ::master_layer::InitCircularTrajectoryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::master_layer::InitCircularTrajectory >::value();
  }
  static const char* value(const ::master_layer::InitCircularTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::master_layer::InitCircularTrajectoryRequest> should match
// service_traits::DataType< ::master_layer::InitCircularTrajectory >
template<>
struct DataType< ::master_layer::InitCircularTrajectoryRequest>
{
  static const char* value()
  {
    return DataType< ::master_layer::InitCircularTrajectory >::value();
  }
  static const char* value(const ::master_layer::InitCircularTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::master_layer::InitCircularTrajectoryResponse> should match
// service_traits::MD5Sum< ::master_layer::InitCircularTrajectory >
template<>
struct MD5Sum< ::master_layer::InitCircularTrajectoryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::master_layer::InitCircularTrajectory >::value();
  }
  static const char* value(const ::master_layer::InitCircularTrajectoryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::master_layer::InitCircularTrajectoryResponse> should match
// service_traits::DataType< ::master_layer::InitCircularTrajectory >
template<>
struct DataType< ::master_layer::InitCircularTrajectoryResponse>
{
  static const char* value()
  {
    return DataType< ::master_layer::InitCircularTrajectory >::value();
  }
  static const char* value(const ::master_layer::InitCircularTrajectoryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MASTER_LAYER_MESSAGE_INITCIRCULARTRAJECTORY_H
