// Generated by gencpp from file master_layer/PingerFrontTarget.msg
// DO NOT EDIT!


#ifndef MASTER_LAYER_MESSAGE_PINGERFRONTTARGET_H
#define MASTER_LAYER_MESSAGE_PINGERFRONTTARGET_H

#include <ros/service_traits.h>


#include <master_layer/PingerFrontTargetRequest.h>
#include <master_layer/PingerFrontTargetResponse.h>


namespace master_layer
{

struct PingerFrontTarget
{

typedef PingerFrontTargetRequest Request;
typedef PingerFrontTargetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PingerFrontTarget
} // namespace master_layer


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::master_layer::PingerFrontTarget > {
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::master_layer::PingerFrontTarget&) { return value(); }
};

template<>
struct DataType< ::master_layer::PingerFrontTarget > {
  static const char* value()
  {
    return "master_layer/PingerFrontTarget";
  }

  static const char* value(const ::master_layer::PingerFrontTarget&) { return value(); }
};


// service_traits::MD5Sum< ::master_layer::PingerFrontTargetRequest> should match
// service_traits::MD5Sum< ::master_layer::PingerFrontTarget >
template<>
struct MD5Sum< ::master_layer::PingerFrontTargetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::master_layer::PingerFrontTarget >::value();
  }
  static const char* value(const ::master_layer::PingerFrontTargetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::master_layer::PingerFrontTargetRequest> should match
// service_traits::DataType< ::master_layer::PingerFrontTarget >
template<>
struct DataType< ::master_layer::PingerFrontTargetRequest>
{
  static const char* value()
  {
    return DataType< ::master_layer::PingerFrontTarget >::value();
  }
  static const char* value(const ::master_layer::PingerFrontTargetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::master_layer::PingerFrontTargetResponse> should match
// service_traits::MD5Sum< ::master_layer::PingerFrontTarget >
template<>
struct MD5Sum< ::master_layer::PingerFrontTargetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::master_layer::PingerFrontTarget >::value();
  }
  static const char* value(const ::master_layer::PingerFrontTargetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::master_layer::PingerFrontTargetResponse> should match
// service_traits::DataType< ::master_layer::PingerFrontTarget >
template<>
struct DataType< ::master_layer::PingerFrontTargetResponse>
{
  static const char* value()
  {
    return DataType< ::master_layer::PingerFrontTarget >::value();
  }
  static const char* value(const ::master_layer::PingerFrontTargetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MASTER_LAYER_MESSAGE_PINGERFRONTTARGET_H
