// Generated by gencpp from file master_layer/PoseReach.msg
// DO NOT EDIT!


#ifndef MASTER_LAYER_MESSAGE_POSEREACH_H
#define MASTER_LAYER_MESSAGE_POSEREACH_H

#include <ros/service_traits.h>


#include <master_layer/PoseReachRequest.h>
#include <master_layer/PoseReachResponse.h>


namespace master_layer
{

struct PoseReach
{

typedef PoseReachRequest Request;
typedef PoseReachResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PoseReach
} // namespace master_layer


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::master_layer::PoseReach > {
  static const char* value()
  {
    return "ffa2c66b3c6d42e336d8ff2c023e44f2";
  }

  static const char* value(const ::master_layer::PoseReach&) { return value(); }
};

template<>
struct DataType< ::master_layer::PoseReach > {
  static const char* value()
  {
    return "master_layer/PoseReach";
  }

  static const char* value(const ::master_layer::PoseReach&) { return value(); }
};


// service_traits::MD5Sum< ::master_layer::PoseReachRequest> should match
// service_traits::MD5Sum< ::master_layer::PoseReach >
template<>
struct MD5Sum< ::master_layer::PoseReachRequest>
{
  static const char* value()
  {
    return MD5Sum< ::master_layer::PoseReach >::value();
  }
  static const char* value(const ::master_layer::PoseReachRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::master_layer::PoseReachRequest> should match
// service_traits::DataType< ::master_layer::PoseReach >
template<>
struct DataType< ::master_layer::PoseReachRequest>
{
  static const char* value()
  {
    return DataType< ::master_layer::PoseReach >::value();
  }
  static const char* value(const ::master_layer::PoseReachRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::master_layer::PoseReachResponse> should match
// service_traits::MD5Sum< ::master_layer::PoseReach >
template<>
struct MD5Sum< ::master_layer::PoseReachResponse>
{
  static const char* value()
  {
    return MD5Sum< ::master_layer::PoseReach >::value();
  }
  static const char* value(const ::master_layer::PoseReachResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::master_layer::PoseReachResponse> should match
// service_traits::DataType< ::master_layer::PoseReach >
template<>
struct DataType< ::master_layer::PoseReachResponse>
{
  static const char* value()
  {
    return DataType< ::master_layer::PoseReach >::value();
  }
  static const char* value(const ::master_layer::PoseReachResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MASTER_LAYER_MESSAGE_POSEREACH_H
