// Generated by gencpp from file master_layer/Pressure.msg
// DO NOT EDIT!


#ifndef MASTER_LAYER_MESSAGE_PRESSURE_H
#define MASTER_LAYER_MESSAGE_PRESSURE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace master_layer
{
template <class ContainerAllocator>
struct Pressure_
{
  typedef Pressure_<ContainerAllocator> Type;

  Pressure_()
    : header()
    , fluid_pressure(0.0)  {
    }
  Pressure_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , fluid_pressure(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _fluid_pressure_type;
  _fluid_pressure_type fluid_pressure;





  typedef boost::shared_ptr< ::master_layer::Pressure_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::master_layer::Pressure_<ContainerAllocator> const> ConstPtr;

}; // struct Pressure_

typedef ::master_layer::Pressure_<std::allocator<void> > Pressure;

typedef boost::shared_ptr< ::master_layer::Pressure > PressurePtr;
typedef boost::shared_ptr< ::master_layer::Pressure const> PressureConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::master_layer::Pressure_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::master_layer::Pressure_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::master_layer::Pressure_<ContainerAllocator1> & lhs, const ::master_layer::Pressure_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.fluid_pressure == rhs.fluid_pressure;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::master_layer::Pressure_<ContainerAllocator1> & lhs, const ::master_layer::Pressure_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace master_layer

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::master_layer::Pressure_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::master_layer::Pressure_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::master_layer::Pressure_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::master_layer::Pressure_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::master_layer::Pressure_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::master_layer::Pressure_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::master_layer::Pressure_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c1e5cbdea79d3bac69c5dcce46192d44";
  }

  static const char* value(const ::master_layer::Pressure_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc1e5cbdea79d3bacULL;
  static const uint64_t static_value2 = 0x69c5dcce46192d44ULL;
};

template<class ContainerAllocator>
struct DataType< ::master_layer::Pressure_<ContainerAllocator> >
{
  static const char* value()
  {
    return "master_layer/Pressure";
  }

  static const char* value(const ::master_layer::Pressure_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::master_layer::Pressure_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Single pressure reading.  This message is appropriate for measuring the\n"
"# pressure inside of a fluid (air, water, etc).  This also includes\n"
"# atmospheric or barometric pressure.\n"
"\n"
"Header header             # timestamp of the measurement\n"
"                          # frame_id is the location of the pressure sensor\n"
"\n"
"float32 fluid_pressure    # Absolute pressure reading in Pascals\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::master_layer::Pressure_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::master_layer::Pressure_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.fluid_pressure);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Pressure_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::master_layer::Pressure_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::master_layer::Pressure_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "fluid_pressure: ";
    Printer<float>::stream(s, indent + "  ", v.fluid_pressure);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MASTER_LAYER_MESSAGE_PRESSURE_H
