// Generated by gencpp from file master_layer/RequestMarkerAngle.msg
// DO NOT EDIT!


#ifndef MASTER_LAYER_MESSAGE_REQUESTMARKERANGLE_H
#define MASTER_LAYER_MESSAGE_REQUESTMARKERANGLE_H

#include <ros/service_traits.h>


#include <master_layer/RequestMarkerAngleRequest.h>
#include <master_layer/RequestMarkerAngleResponse.h>


namespace master_layer
{

struct RequestMarkerAngle
{

typedef RequestMarkerAngleRequest Request;
typedef RequestMarkerAngleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RequestMarkerAngle
} // namespace master_layer


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::master_layer::RequestMarkerAngle > {
  static const char* value()
  {
    return "12546bcf65390528ad1f611260f56054";
  }

  static const char* value(const ::master_layer::RequestMarkerAngle&) { return value(); }
};

template<>
struct DataType< ::master_layer::RequestMarkerAngle > {
  static const char* value()
  {
    return "master_layer/RequestMarkerAngle";
  }

  static const char* value(const ::master_layer::RequestMarkerAngle&) { return value(); }
};


// service_traits::MD5Sum< ::master_layer::RequestMarkerAngleRequest> should match
// service_traits::MD5Sum< ::master_layer::RequestMarkerAngle >
template<>
struct MD5Sum< ::master_layer::RequestMarkerAngleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::master_layer::RequestMarkerAngle >::value();
  }
  static const char* value(const ::master_layer::RequestMarkerAngleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::master_layer::RequestMarkerAngleRequest> should match
// service_traits::DataType< ::master_layer::RequestMarkerAngle >
template<>
struct DataType< ::master_layer::RequestMarkerAngleRequest>
{
  static const char* value()
  {
    return DataType< ::master_layer::RequestMarkerAngle >::value();
  }
  static const char* value(const ::master_layer::RequestMarkerAngleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::master_layer::RequestMarkerAngleResponse> should match
// service_traits::MD5Sum< ::master_layer::RequestMarkerAngle >
template<>
struct MD5Sum< ::master_layer::RequestMarkerAngleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::master_layer::RequestMarkerAngle >::value();
  }
  static const char* value(const ::master_layer::RequestMarkerAngleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::master_layer::RequestMarkerAngleResponse> should match
// service_traits::DataType< ::master_layer::RequestMarkerAngle >
template<>
struct DataType< ::master_layer::RequestMarkerAngleResponse>
{
  static const char* value()
  {
    return DataType< ::master_layer::RequestMarkerAngle >::value();
  }
  static const char* value(const ::master_layer::RequestMarkerAngleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MASTER_LAYER_MESSAGE_REQUESTMARKERANGLE_H
