// Generated by gencpp from file master_layer/TargetNormalRequest.msg
// DO NOT EDIT!


#ifndef MASTER_LAYER_MESSAGE_TARGETNORMALREQUEST_H
#define MASTER_LAYER_MESSAGE_TARGETNORMALREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace master_layer
{
template <class ContainerAllocator>
struct TargetNormalRequest_
{
  typedef TargetNormalRequest_<ContainerAllocator> Type;

  TargetNormalRequest_()
    : task()  {
    }
  TargetNormalRequest_(const ContainerAllocator& _alloc)
    : task(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _task_type;
  _task_type task;





  typedef boost::shared_ptr< ::master_layer::TargetNormalRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::master_layer::TargetNormalRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TargetNormalRequest_

typedef ::master_layer::TargetNormalRequest_<std::allocator<void> > TargetNormalRequest;

typedef boost::shared_ptr< ::master_layer::TargetNormalRequest > TargetNormalRequestPtr;
typedef boost::shared_ptr< ::master_layer::TargetNormalRequest const> TargetNormalRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::master_layer::TargetNormalRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::master_layer::TargetNormalRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::master_layer::TargetNormalRequest_<ContainerAllocator1> & lhs, const ::master_layer::TargetNormalRequest_<ContainerAllocator2> & rhs)
{
  return lhs.task == rhs.task;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::master_layer::TargetNormalRequest_<ContainerAllocator1> & lhs, const ::master_layer::TargetNormalRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace master_layer

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::master_layer::TargetNormalRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::master_layer::TargetNormalRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::master_layer::TargetNormalRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::master_layer::TargetNormalRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::master_layer::TargetNormalRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::master_layer::TargetNormalRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::master_layer::TargetNormalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0ece8f504419f7ca4d91b277e47ff617";
  }

  static const char* value(const ::master_layer::TargetNormalRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0ece8f504419f7caULL;
  static const uint64_t static_value2 = 0x4d91b277e47ff617ULL;
};

template<class ContainerAllocator>
struct DataType< ::master_layer::TargetNormalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "master_layer/TargetNormalRequest";
  }

  static const char* value(const ::master_layer::TargetNormalRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::master_layer::TargetNormalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string task\n"
;
  }

  static const char* value(const ::master_layer::TargetNormalRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::master_layer::TargetNormalRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.task);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TargetNormalRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::master_layer::TargetNormalRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::master_layer::TargetNormalRequest_<ContainerAllocator>& v)
  {
    s << indent << "task: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.task);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MASTER_LAYER_MESSAGE_TARGETNORMALREQUEST_H
