// Generated by gencpp from file master_layer/VerifyObjectRequest.msg
// DO NOT EDIT!


#ifndef MASTER_LAYER_MESSAGE_VERIFYOBJECTREQUEST_H
#define MASTER_LAYER_MESSAGE_VERIFYOBJECTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace master_layer
{
template <class ContainerAllocator>
struct VerifyObjectRequest_
{
  typedef VerifyObjectRequest_<ContainerAllocator> Type;

  VerifyObjectRequest_()
    : object()  {
    }
  VerifyObjectRequest_(const ContainerAllocator& _alloc)
    : object(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _object_type;
  _object_type object;





  typedef boost::shared_ptr< ::master_layer::VerifyObjectRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::master_layer::VerifyObjectRequest_<ContainerAllocator> const> ConstPtr;

}; // struct VerifyObjectRequest_

typedef ::master_layer::VerifyObjectRequest_<std::allocator<void> > VerifyObjectRequest;

typedef boost::shared_ptr< ::master_layer::VerifyObjectRequest > VerifyObjectRequestPtr;
typedef boost::shared_ptr< ::master_layer::VerifyObjectRequest const> VerifyObjectRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::master_layer::VerifyObjectRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::master_layer::VerifyObjectRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::master_layer::VerifyObjectRequest_<ContainerAllocator1> & lhs, const ::master_layer::VerifyObjectRequest_<ContainerAllocator2> & rhs)
{
  return lhs.object == rhs.object;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::master_layer::VerifyObjectRequest_<ContainerAllocator1> & lhs, const ::master_layer::VerifyObjectRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace master_layer

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::master_layer::VerifyObjectRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::master_layer::VerifyObjectRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::master_layer::VerifyObjectRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::master_layer::VerifyObjectRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::master_layer::VerifyObjectRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::master_layer::VerifyObjectRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::master_layer::VerifyObjectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d32a80a49357522333ff3e758d0474bf";
  }

  static const char* value(const ::master_layer::VerifyObjectRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd32a80a493575223ULL;
  static const uint64_t static_value2 = 0x33ff3e758d0474bfULL;
};

template<class ContainerAllocator>
struct DataType< ::master_layer::VerifyObjectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "master_layer/VerifyObjectRequest";
  }

  static const char* value(const ::master_layer::VerifyObjectRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::master_layer::VerifyObjectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string object\n"
;
  }

  static const char* value(const ::master_layer::VerifyObjectRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::master_layer::VerifyObjectRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.object);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VerifyObjectRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::master_layer::VerifyObjectRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::master_layer::VerifyObjectRequest_<ContainerAllocator>& v)
  {
    s << indent << "object: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.object);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MASTER_LAYER_MESSAGE_VERIFYOBJECTREQUEST_H
