// Generated by gencpp from file master_layer/VerifyObject.msg
// DO NOT EDIT!


#ifndef MASTER_LAYER_MESSAGE_VERIFYOBJECT_H
#define MASTER_LAYER_MESSAGE_VERIFYOBJECT_H

#include <ros/service_traits.h>


#include <master_layer/VerifyObjectRequest.h>
#include <master_layer/VerifyObjectResponse.h>


namespace master_layer
{

struct VerifyObject
{

typedef VerifyObjectRequest Request;
typedef VerifyObjectResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct VerifyObject
} // namespace master_layer


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::master_layer::VerifyObject > {
  static const char* value()
  {
    return "e368229d1bcc6909c13f55e3c54b5c10";
  }

  static const char* value(const ::master_layer::VerifyObject&) { return value(); }
};

template<>
struct DataType< ::master_layer::VerifyObject > {
  static const char* value()
  {
    return "master_layer/VerifyObject";
  }

  static const char* value(const ::master_layer::VerifyObject&) { return value(); }
};


// service_traits::MD5Sum< ::master_layer::VerifyObjectRequest> should match
// service_traits::MD5Sum< ::master_layer::VerifyObject >
template<>
struct MD5Sum< ::master_layer::VerifyObjectRequest>
{
  static const char* value()
  {
    return MD5Sum< ::master_layer::VerifyObject >::value();
  }
  static const char* value(const ::master_layer::VerifyObjectRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::master_layer::VerifyObjectRequest> should match
// service_traits::DataType< ::master_layer::VerifyObject >
template<>
struct DataType< ::master_layer::VerifyObjectRequest>
{
  static const char* value()
  {
    return DataType< ::master_layer::VerifyObject >::value();
  }
  static const char* value(const ::master_layer::VerifyObjectRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::master_layer::VerifyObjectResponse> should match
// service_traits::MD5Sum< ::master_layer::VerifyObject >
template<>
struct MD5Sum< ::master_layer::VerifyObjectResponse>
{
  static const char* value()
  {
    return MD5Sum< ::master_layer::VerifyObject >::value();
  }
  static const char* value(const ::master_layer::VerifyObjectResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::master_layer::VerifyObjectResponse> should match
// service_traits::DataType< ::master_layer::VerifyObject >
template<>
struct DataType< ::master_layer::VerifyObjectResponse>
{
  static const char* value()
  {
    return DataType< ::master_layer::VerifyObject >::value();
  }
  static const char* value(const ::master_layer::VerifyObjectResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MASTER_LAYER_MESSAGE_VERIFYOBJECT_H
