// Generated by gencpp from file odom_dvl_imu/SetWorldXYOffset.msg
// DO NOT EDIT!


#ifndef ODOM_DVL_IMU_MESSAGE_SETWORLDXYOFFSET_H
#define ODOM_DVL_IMU_MESSAGE_SETWORLDXYOFFSET_H

#include <ros/service_traits.h>


#include <odom_dvl_imu/SetWorldXYOffsetRequest.h>
#include <odom_dvl_imu/SetWorldXYOffsetResponse.h>


namespace odom_dvl_imu
{

struct SetWorldXYOffset
{

typedef SetWorldXYOffsetRequest Request;
typedef SetWorldXYOffsetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetWorldXYOffset
} // namespace odom_dvl_imu


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::odom_dvl_imu::SetWorldXYOffset > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::odom_dvl_imu::SetWorldXYOffset&) { return value(); }
};

template<>
struct DataType< ::odom_dvl_imu::SetWorldXYOffset > {
  static const char* value()
  {
    return "odom_dvl_imu/SetWorldXYOffset";
  }

  static const char* value(const ::odom_dvl_imu::SetWorldXYOffset&) { return value(); }
};


// service_traits::MD5Sum< ::odom_dvl_imu::SetWorldXYOffsetRequest> should match
// service_traits::MD5Sum< ::odom_dvl_imu::SetWorldXYOffset >
template<>
struct MD5Sum< ::odom_dvl_imu::SetWorldXYOffsetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::odom_dvl_imu::SetWorldXYOffset >::value();
  }
  static const char* value(const ::odom_dvl_imu::SetWorldXYOffsetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::odom_dvl_imu::SetWorldXYOffsetRequest> should match
// service_traits::DataType< ::odom_dvl_imu::SetWorldXYOffset >
template<>
struct DataType< ::odom_dvl_imu::SetWorldXYOffsetRequest>
{
  static const char* value()
  {
    return DataType< ::odom_dvl_imu::SetWorldXYOffset >::value();
  }
  static const char* value(const ::odom_dvl_imu::SetWorldXYOffsetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::odom_dvl_imu::SetWorldXYOffsetResponse> should match
// service_traits::MD5Sum< ::odom_dvl_imu::SetWorldXYOffset >
template<>
struct MD5Sum< ::odom_dvl_imu::SetWorldXYOffsetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::odom_dvl_imu::SetWorldXYOffset >::value();
  }
  static const char* value(const ::odom_dvl_imu::SetWorldXYOffsetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::odom_dvl_imu::SetWorldXYOffsetResponse> should match
// service_traits::DataType< ::odom_dvl_imu::SetWorldXYOffset >
template<>
struct DataType< ::odom_dvl_imu::SetWorldXYOffsetResponse>
{
  static const char* value()
  {
    return DataType< ::odom_dvl_imu::SetWorldXYOffset >::value();
  }
  static const char* value(const ::odom_dvl_imu::SetWorldXYOffsetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ODOM_DVL_IMU_MESSAGE_SETWORLDXYOFFSET_H
